### ISSUE TITLE
Fix invoice on front-end

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#100]
1. Space between invoice fee and currecy and change to SEK due to WooCommerce default
En fakturaavgift på 19.90kr tillkommer på orderbeloppet. --> En fakturaavgift på 19.90 SEK tillkommer på orderbeloppet.
2. If get adress is active the personnummer / organisationsnummer should not be visible (same logic as on Magento with mandatory and so on)
3. If get adress is inactive the "Personnummer / Organisationsnummer" should be on one row.
4. Same text as on Magento:
Min e-post, test@testdomain.com, är korrekt och får användas för fakturering. Jag bekräftar även köpvillkor för fakturabetalning. och accepterar betalningsansvaret.
to
Min e-postadress, test@teststore123.com, är korrekt och får användas för fakturering. Jag bekräftar även  köpvillkoren och accepterar betalningsansvaret.

**Comment by Boxedsolutions** [comment]
Its WooCommerce function wc_price($this->invoice_fee+$taxAmount)) that makes the cost that way.

**Comment by andyjohansson** [comment]
1. But this is displayed the way I want it?
<img width="477" alt="skarmavbild 2015-08-03 kl 09 07 24" src="https://cloud.githubusercontent.com/assets/4968755/9032454/1769a6a8-39bf-11e5-9856-30de89f1c17e.png">

2. Fixed.

3. Fixed.

4. Fixed.

**Comment by Boxedsolutions** [comment]
Then we manually parse the invoice fee string to make it so.

**Comment by andyjohansson** [comment]
Ok, then we cancel that one. It is fixed.
