### ISSUE TITLE
Fakturavgift is one word

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#102]
Displayed in the checkout.
<img width="792" alt="skarmavbild 2015-08-03 kl 09 03 46" src="https://cloud.githubusercontent.com/assets/4968755/9032406/92c4dbb6-39be-11e5-8807-49485fdb240f.png">

**Comment by andyjohansson** [comment]
Also in back-end.
<img width="747" alt="skarmavbild 2015-08-03 kl 09 24 17" src="https://cloud.githubusercontent.com/assets/4968755/9032696/70582e40-39c1-11e5-8260-b1c1c2176533.png">

**Comment by Boxedsolutions** [comment]
Should be fixed
