### ISSUE TITLE
Are we only showing the personummer / organisationsnummer if it is an country that is applicable for invoice / partpayment?

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#103]

**Comment by Boxedsolutions** [comment]
Good question, I think its visible but not required as the other payment alternatives are not needing this.

**Comment by andyjohansson** [comment]
Yes, but people can get confused. Will move this to the 2.1 release but this should be implemented soon.

**Comment by andyjohansson** [comment]
Pushing to future release.

**Comment by Boxedsolutions** [comment]
Suggesting move to future release.
