### ISSUE TITLE
If the social security number is validated, mark it validated as other input fields

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#106]
![skarmavbild 2015-08-03 kl 14 26 47](https://cloud.githubusercontent.com/assets/4968755/9037437/b516c2ec-39eb-11e5-9866-d9472fbe15d9.png)

**Comment by andyjohansson** [comment]
Also mark it as unvalidated in the same way as other input fields. See video --> https://v.usetapes.com/sSQZvthlsl

**Comment by andyjohansson** [comment]
Implement the same logic if get_adress is not enabled.

**Comment by Boxedsolutions** [comment]
It should be implemented, but its not that easy to do with getAddress not enabled. Some woocommerce styling issue

**Comment by andyjohansson** [comment]
Isn´t it only due to how we have made our markup?

**Comment by Boxedsolutions** [comment]
Now when the error codes is 9015|9016|2207|1001 the ssn field is marked invalid.

**Comment by andyjohansson** [comment]
I think you broke the billmatepopup.js

![skarmavbild 2015-08-04 kl 09 43 26](https://cloud.githubusercontent.com/assets/4968755/9055670/4a23a020-3a8d-11e5-870b-bd1316ec0b65.png)
