### ISSUE TITLE
Invoice fee visible ex. VAT in overview

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#107]
Anyway to get the invoice fee to be shown incl. VAT in the overview (top) of this image? Right now it´s shown with and without VAT on the same page. Note that we should not go against the WooCoomerce standard, this is more of a question.

![skarmavbild 2015-08-03 kl 14 30 21](https://cloud.githubusercontent.com/assets/4968755/9037497/48f0ebbe-39ec-11e5-9793-1d3271340600.png)

**Comment by Boxedsolutions** [comment]
I added Shipping to use as a Reference and it seems that the sum there is ex.vat

**Comment by andyjohansson** [comment]
So is this fixed or not?

**Comment by Boxedsolutions** [comment]
This is fixed

**Comment by andyjohansson** [comment]
Sure?
<img width="716" alt="skarmavbild 2015-08-03 kl 21 08 14" src="https://cloud.githubusercontent.com/assets/4968755/9045498/c9d56804-3a23-11e5-90d8-d8eb935948ae.png">

**Comment by Boxedsolutions** [comment]
We can change it but as the Shipping fee is shown without VAT it can be confusing if Handling fee is shown with and the total will not be correct. We are using woocommerce add_fee here.

**Comment by andyjohansson** [comment]
Let´s close this for now and see if we get any complaints.
