### ISSUE TITLE
Why do we have two error messages for the same error?

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#108]
![skarmavbild 2015-08-03 kl 14 32 16](https://cloud.githubusercontent.com/assets/4968755/9037522/7a6178ee-39ec-11e5-8a41-b027757da247.png)

**Comment by Boxedsolutions** [comment]
It should be fixed

**Comment by andyjohansson** [comment]
Looks good but in this case we should make the social security input as invalid? This is also true for the denied error code for live payments.
<img width="716" alt="skarmavbild 2015-08-03 kl 20 53 43" src="https://cloud.githubusercontent.com/assets/4968755/9045189/ce671acc-3a21-11e5-8bee-79fdf3c68ac8.png">

**Comment by Boxedsolutions** [comment]
Should be fixed.

**Comment by andyjohansson** [comment]
Can't verify not due to the billmatepopup.js break
