### ISSUE TITLE
If i post a invalid social security number then the input field in get adress should be invalidated.

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#111]
<img width="729" alt="skarmavbild 2015-08-03 kl 21 17 36" src="https://cloud.githubusercontent.com/assets/4968755/9045658/263252fa-3a25-11e5-99cb-eb8a7b09ead8.png">

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Not completely working here.
![skarmavbild 2015-08-05 kl 14 19 46](https://cloud.githubusercontent.com/assets/4968755/9085446/17b778c8-3b7d-11e5-89f0-3b3665114ee6.png)

**Comment by Boxedsolutions** [comment]
Changed the logic to fix this.
<img width="767" alt="skarmavbild 2015-08-07 kl 10 30 06" src="https://cloud.githubusercontent.com/assets/8977650/9131823/4ded7b54-3cef-11e5-8419-81e68784fdfc.png">
