### ISSUE TITLE
verify our Icon filters

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/woocommerce#131]

**Comment by andyjohansson** [comment]
What is this, could you elaborate?

**Comment by Boxedsolutions** [comment]
This is a wordpress filter for our Icons. Example.

To make it easier for people with different templates to change dimensions and so on. Without touching our core files and code.
 apply_filters( 'billmate_partpayment_icon', $billmate_partpayment_icon );

**Comment by andyjohansson** [comment]
How would this work, through a setting in the back-end?

**Comment by Boxedsolutions** [comment]
No it would work in the usual way Wordpress uses templates in their functions.php

**Comment by Boxedsolutions** [comment]
https://developer.wordpress.org/reference/functions/add_filter/

**Comment by Boxedsolutions** [comment]
Should be implemented in cc57e11
