### ISSUE TITLE
Log invoice id in the order "händelser"

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#146]

**Comment by Boxedsolutions** [comment]
Does the invoice id shows in order history? @Aviree

**Comment by Aviree** [comment]
Yes i shows correct

**Comment by Aviree** [comment]
It works fine

**Comment by Aviree** [comment]
Don't work with bankpayments

**Comment by andyjohansson** [comment]
@Aviree, don't forget to reasign it back to the developer. In this case @Boxedsolutions.

**Comment by Aviree** [comment]
Works fine
Closing issue
