### ISSUE TITLE
Different order notes for new failed card payment (recurring) out of money and other errors

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#147]

**Comment by Boxedsolutions** [comment]
@andyjohansson Is Billmate Error messages sufficient? Otherwise this is a Api related fix?

**Comment by andyjohansson** [comment]
What does it say right now?

**Comment by Boxedsolutions** [comment]
Its the message from Billmate if there is a code parameter sent otherwise it is sent payment in case of Subscription, subscription payment failed:
