### ISSUE TITLE
Autoactivate on orderstatus

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#149]

**Comment by Boxedsolutions** [comment]
Should be implemented in ec14483f0c85179cb5e62155fe806ee4edd05c3d

**Comment by andyjohansson** [comment]
Is this in the development branch?

**Comment by Boxedsolutions** [comment]
in release-2.2 branch which I currently develop against.

**Comment by andyjohansson** [comment]
Ok, we shouldn't develop against release branchas unless they are ready for testing. Please see http://nvie.com/posts/a-successful-git-branching-model/

**Comment by andyjohansson** [comment]
Since @Aviree will begin testing when we make release candidates.

**Comment by Boxedsolutions** [comment]
Ok, then I guess I named it wrong when i begun develop 2.2. I thought it was not a hotfix, so I used release as name. But what if we should add a branch for tests f.ex test-2.2?

**Comment by Boxedsolutions** [comment]
Did it activate in Billmate online?

**Comment by andyjohansson** [comment]
Will test when I get the teststore.

**Comment by andyjohansson** [comment]
Can you verify @Aviree?

**Comment by Aviree** [comment]
It works fine.
