### ISSUE TITLE
Change standard logo to trustly logo

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#150]

**Comment by andyjohansson** [comment]
Ask for it when you need it.

**Comment by Aviree** [comment]
The logo-size is wrong. Se attached image
![logo](https://cloud.githubusercontent.com/assets/14887835/12265097/702e874e-b93b-11e5-8550-1fd9b81550a9.png)

**Comment by Aviree** [comment]
Tested after changes was made and it looks fine now
close this issue
