### ISSUE TITLE
Ordermails not beeing sent

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#152]
Client reported this.

**Comment by andyjohansson** [comment]
Victor Auren will complement with more info.

**Comment by Boxedsolutions** [comment]
Is the cause of #153

**Comment by Boxedsolutions** [comment]
Verify mails sent

**Comment by Aviree** [comment]
Tested purchases with all four methods and all send an ordermail. I had to activate bankpayment manuell because it got wrong status. It has "Mottagen (Obetald)" even I set the status in settings to Standard. 

I checked Billmate Online and the status was paid.

**Comment by andyjohansson** [comment]
Will test this when I get teststore.

**Comment by Boxedsolutions** [comment]
Is ordermail going out @Aviree

**Comment by Aviree** [comment]
It works with card, invoice and partpayment. But not with bankpayment. It says that it's waiting for payment in the orderstatus in Woocommerce. In API and Billmate online it says Paid.

**Comment by andyjohansson** [comment]
Anything new @Boxedsolutions & @Aviree?

**Comment by Aviree** [comment]
Tested all paymentmethods and it worked as it should. 
Closing Issue
