### ISSUE TITLE
Show notice if Wordfence is activated with Billmate Gateway

### ISSUE THREAD

**Issue by Aviree** [Billmate/woocommerce#153]
[SWE] För att Wordfence och Billmate Gateway ska fungera ihop måste man lägga till Callback IP under Whitelist. För att ställa in det, navigera till Wordfence->Options. Scrolla ner till "Other Options" och vid inställningen "Whitelisted IP addresses that bypass all rules" fyll i IP-nummer 54.194.217.63. 

[ENG] To make Wordfence and Billmate Gateway work toghether you have to add the Callback IP to the whitelist. To do so navigate to Wordfence->Options and then scroll down to "Other Options". Find "Whitelisted IP addresses that bypass all rules" and add the IP 54.194.217.63.

**Comment by Boxedsolutions** [comment]
Check so that if you inactivate and activate that is not become any error messages.

**Comment by Aviree** [comment]
I have tested to inactivate wordfence and proceed with a purchase. Passed with no errors. Activated wordfence again, did a new purchase and it passed with no errors.
