### ISSUE TITLE
Fatal error part payment (delbetalning) after new years eve

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/woocommerce#155]
Hi, I'm getting a fatal error in my store after new years eve, due to invalid payment plans (got invalid after 2015-12-31). The following error (from apache logs) shows up when visiting a single product when the "Show monthly fee on single product pages / Visa månadskostnad på enskilda produkt sidor" option is checked:

```
PHP Fatal error:  Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in ********/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 888, referer: https://www.vapes.se/produkt/startkit/eleaf-ijust-2-sub-ohm-kit/
```

I've tried updating the payment plans to make them valid again, but I get the following fatal error (blank POST request):

```
PHP Fatal error:  Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in *******/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 538, referer: *****/wp-admin/admin.php?page=wc-settings&tab=checkout&section=wc_gateway_billmate_partpayment
```

Our customers are currently unable to purchase anything while part payment is active.

**Comment by andyjohansson** [comment]
Hi @DanielMarklund? Are you still experiencing these issues?

**Comment by DanielMarklund** [comment]
Hi @andyjohansson! It works great now. Thank you for resolving it so fast.

**Comment by andyjohansson** [comment]
No problem, just get in touch if you experience any other issues.
