### ISSUE TITLE
Partpayment show information in both Swedish and English

### ISSUE THREAD

**Issue by Aviree** [Billmate/woocommerce#157]
[ENG]In checkout it present the paymentplans in both english and swedish. It should only show in the selected language. Se picture below. 

[SWE]När man ska betala i kassan så visas delbetalningsplanerna på både svenska och engelska. Det ska bara visa för det valda språket. Se bilden nedan. 

![checkout](https://cloud.githubusercontent.com/assets/14887835/12116630/82d6a12c-b3bb-11e5-93fd-9f799b13aa36.png)

**Comment by Boxedsolutions** [comment]
Please check again.

**Comment by Aviree** [comment]
I did test with the langauge Swedish in the admin-page, and updated the paymentplans. It only presented paymentplans in Swedish. In the webstore it also had the swedish paymentplans. 
I then changed the language to english. Updated the paymentplans, and now it showed only the english paymentplans in both the adminpage and the checkout on the webstore.
