### ISSUE TITLE
Rounding in Billmate Online

### ISSUE THREAD

**Issue by Aviree** [Billmate/woocommerce#158]
[ENG] When I do purchase on products with decimals, it present four decimals in Billmate Online. On the Invoice it shows the correct amount, but in the overview on orders it shows wrong. 
It is the same with all paymentmetohods. The logs is is showing: 
"Total": {
            "withouttax": 15388.33,
            "tax": 2180,
            "rounding": 0,
            "withtax": 17568.33
        }

[SWE] När jag gör testköp på produkter med decmaler så visas det 3-4 decimaler i Billmate Online. På fakturan visas rätt summa med 2 decimaler, men där man ser överblick över alla ordrar visar det fel. 
Loggen visar följande:
"Total": {
            "withouttax": 15388.33,
            "tax": 2180,
            "rounding": 0,
            "withtax": 17568.33
 }

**Comment by andyjohansson** [comment]
Can you verify that everything is OK from plugin side @Boxedsolutions? And then provide me with API log id's to start a ticket on server-side?

**Comment by Boxedsolutions** [comment]
I dont think i can round more without getting issues with the totals.
I will in that case get a issue with the rounding differs from the shop.

apiLogsid
212291

**Comment by Aviree** [comment]
I have tested this again after changes was made and now it works fine.
Closing this issue
