### ISSUE TITLE
Issue with rounding 

### ISSUE THREAD

**Issue by Aviree** [Billmate/woocommerce#161]
When I made an order and paid with card, the rounding was incorrect. It rounded my order with 25 :- on both the invoice and in the API-log. 
See the attached image. 
![apiround](https://cloud.githubusercontent.com/assets/14887835/12262233/f2a9e4bc-b926-11e5-9913-9b28c00c8135.PNG)

**Comment by andyjohansson** [comment]
What's happening here and with all other issues related with release 2.2? We're behind schedule @Aviree & @Boxedsolutions

**Comment by Boxedsolutions** [comment]
I know that @andyjohansson Seems that the rounding issue is only when you use signup fee and a recurring product with a price. It seems that the vat for signup_fee is applied multiple times.

In my opinion its a bug with the Subscription plugin.

**Comment by andyjohansson** [comment]
Can you verify this @Aviree ?

**Comment by Aviree** [comment]
Works after the fee and the subscriptionproduct was calculated in the same amount. Woocommerce use that calculation. It don't work when extracting the startup fee to be specified alone. 
Closing issue
