### ISSUE TITLE
Missing translation for HTML title for common settings

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#164]
See attached image.
<img width="860" alt="skarmavbild_2016-01-25_kl__11_22_48-1" src="https://cloud.githubusercontent.com/assets/4968755/12542555/6e811e2c-c357-11e5-9035-509b3500e6c0.png">

**Comment by Boxedsolutions** [comment]
<img width="397" alt="skarmavbild 2016-01-25 kl 08 50 33" src="https://cloud.githubusercontent.com/assets/8977650/12545241/bd47b0be-c340-11e5-82e9-c8b355414817.png">
Anyone Know if its a special place to translate it then?

**Comment by andyjohansson** [comment]
Sorry, no idea out of the box.

**Comment by Aviree** [comment]
It says "Billmate Inställningar" in swedish and "Billmate Common" in english. Should it be "Billmate Settings" in english instead?

**Comment by Boxedsolutions** [comment]
It says now when English Billmate Settings

**Comment by Aviree** [comment]
Now it's looking good
Issue closed
