### ISSUE TITLE
Post status incomplete. "wc-"

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/woocommerce#175]
We got an e-mail today from a customer who didn't get any confirmation emails etc. We dived into wp-admin to search for the order, but it wasn't there weirdly enough. The payment was registered fine at online.billmate.se, which meant the order existed. So I checked the database and noticed an order having the post_status "wc-" without any appended string such as "pending" etc. I did a quick search in the wp_posts table and found three other orders that had the same "wc-" post_status.

I've tried to replicate this problem without success sadly, so I'm wondering if anyone else has stumbled upon this before. I can't think about any other plugin that could've caused this very issue.

**Update:**
I've compared the API Callbacks from Billmate between the faulty order and a successful one, and nothing looked weird in the diff. The PaymentData.method is 16. I also tried to replicate the issue by creating some test orders, but it seems to be random somehow since I couldn't get the same results.

Billmate Gateway version: 2.1.4
Woocommerce version: 2.4.8
Wordpress version: 4.3.1

I know we're waaaay behind updates. Going to run some updates next week, but since I can't replicate it I'll have no idea if the updates resolve the issue. So if anyone has some ideas on what could've gone wrong and how to replicate, please share.

**Comment by DanielMarklund** [comment]
New update. We've been running the latest version of Billmate (2.2.3), Woocommerce (2.5.3), WordPress (4.4.2) for a week now and this problem is still happening on random occasions. Any ideas?

**Comment by Boxedsolutions** [comment]
It sound strange, 

Do you use standard status for Billmate Bankpay? Is it only bankpay? I think it should have been solved in the next release which hopefully will be released in this week.

**Comment by Boxedsolutions** [comment]
It might have been solved in plugin version 2.2.5
