### ISSUE TITLE
ÅÄÖ issue when checking out 

### ISSUE THREAD

**Issue by victorauren** [Billmate/woocommerce#180]
When checking out with ÅÄÖ in adressfield, an error appears. 
When pop-up shows it displays as picture 1. 
When clicking yes it says the information is not matched with the information saved on the registered number. 
See picture 2
(api_log: 309938)

![picture1](https://cloud.githubusercontent.com/assets/14887835/14247906/b95d5e5a-fa71-11e5-9981-ad8a70300e06.png)
![picture2](https://cloud.githubusercontent.com/assets/14887835/14247905/b95b317a-fa71-11e5-909e-6bd90f506432.png)

**Comment by Boxedsolutions** [comment]
Needs test

**Comment by victorauren** [comment]
Works if changen city, but if I change adderess it doesn't trigger the popup

**Comment by Boxedsolutions** [comment]
Changed logic to match the same number of words in both strings compared

**Comment by victorauren** [comment]
Works fine

Closing issue
