### ISSUE TITLE
Add class for terms link

### ISSUE THREAD

**Issue by ben72** [Billmate/woocommerce#195]
It would be easier to target and modify the terms link on the checkout page with custom css if there was a class associated with the link.

Now I target it with "#payment .payment_methods li .payment_box fieldset a { color: #16B5F0 !important; }

**Comment by ben72** [comment]
Thanks @Boxedsolutions ! =)

**Comment by Boxedsolutions** [comment]
@ben72 I just merged it :)

**Comment by ben72** [comment]
Great! Do you know when the release will be pushed to wp repos? @Boxedsolutions

**Comment by Boxedsolutions** [comment]
@ben72 Probably monday.
