### ISSUE TITLE
Add support for custom checkouts without separate shipping address

### ISSUE THREAD

**Issue by kalorifri** [Billmate/woocommerce#197]
Today when using a WooCommerce checkout that does not have input fields for shipping address the error is returned when paying with Billmate Invoice.

Notice: Undefined index: shipping_first_name in /var/www/html/shop.agi.se/public_html/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-invoice.php on line 612

Notice: Undefined index: shipping_last_name in /var/www/html/shop.agi.se/public_html/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-invoice.php on line 612

Notice: Undefined index: shipping_company in /var/www/html/shop.agi.se/public_html/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-invoice.php on line 612

Make shipping_first_name and other shipping values not mandatory.
Psuedocode example:  shipping_first_name = (is defined) ? shipping_first_name : "";

Or assume if not set shipping have same value as billing.

**Comment by Boxedsolutions** [comment]
An Easy fix would be to check all shipping fields with isset, but Why remove the fields from the checkout, the default thing is to only hide them.
