### ISSUE TITLE
Invoice email information on order confirmation page

### ISSUE THREAD

**Issue by billmate-support** [Billmate/woocommerce#198]
Check if possible to add custom content to the store order confirmation page (thank you).
Check if possible to get payment method of created order.
Check if possible to get customer email for created order.

If all above is possible, include following text

Se: 
Om du har valt att betala med faktura eller delbetalning kan den i samband med leverans skickas separat till er epost customer@email.com eller din fakturaadress.

En: 
If you have selected to pay with invoice or part payment it might be associated with delivery sent separately to your email customer@email.com or your billing address.

**Comment by kalorifri** [comment]
Released in 3.1.1

**Comment by ben72** [comment]
Det hade varit bra att få in detta i orderbekräftelsen till kund också.
