### ISSUE TITLE
Wrong invoice fee ID -  Display something in backend

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#20]
If you enter a wrong invoice fee id in the backend it should display a warning next to the label and input box for it. Maybe in error red?

**Comment by andyjohansson** [comment]
This one should be resolved by using the correct way to select the invoice fee. Correct @Boxedsolutions ?

**Comment by Boxedsolutions** [comment]
With the new way that is planned in 2.0 its resolved as you in 2.0 sets the invoice cost and the correct tax class.

**Comment by andyjohansson** [comment]
Great, leave this one open until implemented and tested then.

**Comment by Boxedsolutions** [comment]
Is the invoice fee working correct @joakim-combain

**Comment by joakim-combain** [comment]
This is an old issue, but yes it works as I was told we had changed it to. I'm sure there are things I haven't tried yet with invoice fee but I will continue testing it. Closing this issue since it's not valid anymore.
