### ISSUE TITLE
Set right version number in api call

### ISSUE THREAD

**Issue by kalorifri** [Billmate/woocommerce#201]
Today, when making an API request it is set that the module version is 2.2.6 
Make sure that the module version that is sent in api requests are same as module version (currently 2.2.8)

**Comment by Boxedsolutions** [comment]
Which request are we talking about? 
I did a search and it seems correct https://github.com/Billmate/woocommerce/search?utf8=%E2%9C%93&q=BILLMATE_CLIENT

**Comment by kalorifri** [comment]
It was a missunderstanding. It is not here the issue was.
