### ISSUE TITLE
Add support for not create new order when changing payment method

### ISSUE THREAD

**Issue by kalorifri** [Billmate/woocommerce#202]
For example, when in checkout card payment is selected, cancel and then selecting invoice payment. 2 orders will be created in admin there the first one is pending card payment and the second one is marked as paid with invoice.

If possible, do not create new order when changing payment method in checkout.

**Comment by ben72** [comment]
När man byter betalsätt efter en misslyckad betalning till t ex Stripe skapas inte en ny order men byter man till något av era betalsätt skapas en ny order vilket är lite irriterande om man vill hålla en ungefärlig räkning på antal ordrar mha order#.

**Comment by ben72** [comment]
Vi hade precis en kund som provade faktura och sedan delbetalning. Båda fallerade vilket resulterade i två misslyckade ordrar och inte bara en. Det vore helt klart bättre om order# behölls även om kunden byter betalsätt.

**Comment by Boxedsolutions** [comment]
Känns lite som om detta måste undersökas. Då det verkar som om att sätter man status failed om exvis kunden misslyckas med faktura/delbetalning så skapar WooCommerce en ny order.

Men vi ska se vad som går att ordna för att förbättra detta.

**Comment by ben72** [comment]
Det verkar som sagt som att andra betalsätt hanterar det på annat sätt så det inte skapas en ny order när kunden misslyckas med ett betalsätt och byter till ett annat. Men det behöver som du säger undersökas mer.

**Comment by ben72** [comment]
@andyjohansson Lade märke till att du stängde alla issues igår förutom min senaste. Varför?
