### ISSUE TITLE
add support for Customer Invoice

### ISSUE THREAD

**Issue by kalorifri** [Billmate/woocommerce#208]
If you use Customer Invoice in WooCoomerce, the customer receive a link to their email where they can pay the order.
On that page, when paying with Billmate Invoice and the given address does not match the address billmate API expect it should display a popup with the expected address and option to use that address.
Instead a blank page is displayed with the content  {"messages":".

An idea of that causing the issue is the plugin use checkout class that in the checkout page but not on the page page the customer received link to.

Please take a look at template for  /woocommerce/templates/checkout/form-pay.php

**Comment by thorbrink** [comment]
What is the current status on this issue?

**Comment by Boxedsolutions** [comment]
The status is that it needs some work to make it work in both cases.
