### ISSUE TITLE
Verify order id

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#21]
Make sure that the plugin works with other plugins that generate other order id´s example - http://www.woothemes.com/products/sequential-order-numbers-pro/

**Comment by andyjohansson** [comment]
Let's take a look at this @Boxedsolutions for the 2.0 release.

**Comment by Boxedsolutions** [comment]
Its Implemented. @joakim-combain  Could you test invoice and PArtpayment so the order id is the same on BO and WooCommerce?

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
