### ISSUE TITLE
Request: support for WooCommerce Currency Switcher

### ISSUE THREAD

**Issue by kalorifri** [Billmate/woocommerce#210]
If possible, support for WooCommerce Currency Switcher would be nice
https://wordpress.org/plugins/woocommerce-currency-switcher/

**Comment by Boxedsolutions** [comment]
It shouldnt be that hard to implement. Check if the WooCommerceCurrencySwitcher plugin exists and if it does use $WOOCS->current_currency

http://currency-switcher.com/codex/

**Comment by kalorifri** [comment]
Fixed in version 3.0.6
