### ISSUE TITLE
Critical: Personnummer is NOT working at the moment!

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/woocommerce#214]
Personnummer (for fast fetching of address and also invoices etc) is currently not working. It does not work in our WooCommerce webshop and also not at https://www.billmatecheckout.se/.

The error message is: "Personnummer / organisationsnummer finns ej i systemet." regardless of input format.

This means that no purchases via faktura / delbetalning are possible at the moment. Are you aware of this bug?

Thanks!

**Comment by DanielMarklund** [comment]
@Boxedsolutions Sorry if this is not the place to report a bug that isn't directly connected to the WooCommerce gateway. Not sure where to report this since Billmate AB is currently not available for technical support. :)

**Comment by ben72** [comment]
I'm seeing the same issue! I'm getting "Personnummer / organisationsnummer finns ej i systemet." when I enter a valid personnummer!

**Comment by DanielMarklund** [comment]
@ben72 

Update after getting in touch with Billmate AB and they are aware of the problem. It's their credit- & personal data provider that are having problems right now (Creditsafe AB I assume). ETA for solution is currently 18:00 / 06:00 PM.

**Comment by Boxedsolutions** [comment]
Seems like it should work now.

**Comment by ben72** [comment]
Yes, works for me now! =)
