### ISSUE TITLE
BillMate has a deprecated constructor (for use with PHP7)

### ISSUE THREAD

**Issue by senlin** [Billmate/woocommerce#217]
Hi,

I already had left this more than 3 weeks ago on the [WP.org forums](https://wordpress.org/support/topic/billmate-has-a-deprecated-constructor-for-use-with-php7/), but perhaps here it receives more attention.

As per title, plugin uses a deprecated constructor method and throws notices when on PHP7.

To solve the issue is easy.

line 32 of `/library/Billmate.php` now reads:

`function BillMate($id,$key,$ssl=true,$test=false,$debug=false,$referer=array()){`

change it to:

`function __construct($id,$key,$ssl=true,$test=false,$debug=false,$referer=array()){`

and you’re set.

Hope this helps.

**Comment by Boxedsolutions** [comment]
Should be fixed in latest release. 
Fixed this in this commit https://github.com/Billmate/woocommerce/commit/5e5417964e041344f366a6d4dcb25c638e9a4aca

**Comment by senlin** [comment]
Cool thanks, I didn;t know as I had not heard anything on earlier mentioned ticket at WP.org.

Perhaps an idea to add a line that says that you don't offer support on the forums and put a sticky topic up on the forums that says the same thing? I do that to all my plugins ([example](https://wordpress.org/plugins/so-clean-up-wp-seo/))and most of the people hop over to Github to open a ticket. 
_Of course some don't, but then it's up to you to decide to assist or not..._

**Comment by kalorifri** [comment]
Fixed in 3.0
