### ISSUE TITLE
main plugin folder name different on Github and WP.org

### ISSUE THREAD

**Issue by senlin** [Billmate/woocommerce#218]
As the title suggests, the folder name on WordPress is 
`billmate-payment-gateway-for-woocommerce` whereas here on Github it is `woocommerce-gateway-billmate`.
Not only that, but the instructions over at WP.org speak of

> 3. Upload the folder “woocommerce-gateway-billmate” to /wp-content/plugins

_from [installation tab](https://wordpress.org/plugins/billmate-payment-gateway-for-woocommerce/#installation)_

I would like to suggest to either change the folder here on Github or send an email to plugins@wordpress.org and ask them to change it for you (they do make changes on some occasions).

While you're at it, I would also like to suggest to address [this](https://github.com/Billmate/woocommerce/issues/216#issuecomment-296975435)

Cheers!

**Comment by Boxedsolutions** [comment]
I think change it could create som issues with people that uses this release from here. 
But we shall think it through

**Comment by senlin** [comment]
That is fine, but then please update the readme file of the version that you release on WP. 

Now the installation instructions in the [Readme.txt file](http://plugins.svn.wordpress.org/billmate-payment-gateway-for-woocommerce/tags/3.0.0.2/Readme.txt) are simply wrong

**Comment by Boxedsolutions** [comment]
I will add this to next release.

**Comment by senlin** [comment]
sorry, didn't meant o close it :) thanks for adding it to your milestone!
