### ISSUE TITLE
Improve compatibility PHP 7 (A non-numeric value encountered)

### ISSUE THREAD

**Issue by kalorifri** [Billmate/woocommerce#219]
When using PHP 7 and select Billmate invoice on store checkout page, error below is displayed: 

Warning: A non-numeric value encountered in /Users/patrik/Sites/marks-kattens/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-invoice.php on line 327
Warning: A non-numeric value encountered in /Users/patrik/Sites/marks-kattens/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-invoice.php on line 332

**Comment by Boxedsolutions** [comment]
Its PHP 7.1 that sends that warning.

**Comment by arvdsn** [comment]
I was the one reporting this issue, so if you need to get in touch with me quickly you can just tag me here.

**Comment by Boxedsolutions** [comment]
@arvdsn Just a quick question do you have any invoice fee or min and max totals? For the payment gateway?

My guess is that it is what makes the warning, but we will of course fix it.

**Comment by arvdsn** [comment]
@Boxedsolutions We do, min 0,00 and max 1000000,00 is set (invoice inactive if sum i lower or higher). We do not have any invoice fee set though.

**Comment by Boxedsolutions** [comment]
hmm, Can it be that you uses decimalcomma instead of decimalpoint? Will it fix it if you change to points instead. 
But will create a solution for it.

**Comment by arvdsn** [comment]
@Boxedsolutions Replacing with decimal points did solve the issue. Awesome!

**Comment by Boxedsolutions** [comment]
@arvdsn  Great. Then I know how to solve it.

**Comment by arvdsn** [comment]
FYI: We updated to PHP7.1 now on live, and the issue appeared again. Switching to dot instead of comma didn't work either, but removing the limits all together worked.

WC: 3.0.7
WP:	4.7.5
BillMate GW: 3.0.0.2

**Comment by Boxedsolutions** [comment]
@arvdsn It should be fixed in the next release. We are working on a solution to fix this.
