### ISSUE TITLE
I get error message when fetching pclasses

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#23]
I Get this error message when trying to fetch pclasses.

Fatal error: Call to undefined function wc_add_notice() in /public_html/wp-content/plugins/woocommerce-gateway-billmate/commonfunctions.php on line 18

**Comment by andyjohansson** [comment]
fixed in release-1.23

**Comment by andyjohansson** [comment]
Fixed with commit 8c2bd7797bd4c49dfe527b1497a2d7223000b0f1
