### ISSUE TITLE
Verify that autoactivate works on order settings flow

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#233]
One store which uses Checkout has had this bug.

**Comment by andyjohansson** [comment]
Same order status for accepted as in activated does not trigger activatePayment

**Comment by Boxedsolutions** [comment]
Tested and if rounding is more than ,50 it cant activate. Although the logic seems to work.

**Comment by andyjohansson** [comment]
@kalorifri have made a change for this. Should work now.
