### ISSUE TITLE
Manual order support

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#24]
When you create a manual order with the invoice or partpayment as payment gateway --> create order in Billmate Online.

**Comment by andyjohansson** [comment]
Pushing to future release.

**Comment by Boxedsolutions** [comment]
Its now possible to make an order and let the customer checkout

**Comment by Boxedsolutions** [comment]
Pushing to future, invoice and partpayment needs to be completely rewritten

**Comment by kalorifri** [comment]
Closing issue. Support exists for pay order created in admin and customer is paying in the store checkout with the "Customer payment page" url found on order in store admin.
