### ISSUE TITLE
Bankbetalning issues

### ISSUE THREAD

**Issue by ben72** [Billmate/woocommerce#240]
I've seen many times now that orders "Via Bankbetalning" fails. And then sometimes a successful order with "Via Billmate Bankbetalning" comes in after that.
Why doesn't both use the same string?

In the settings I have "Bankbetalning".

Screenshot:
https://www.dropbox.com/s/w8n53xyht5ziqzg/Selection_00093.jpg?dl=0

**Comment by kalorifri** [comment]
Where did you change the setting to "Bankbetalning" ?

**Comment by ben72** [comment]
WooCommerce->Inställningar->Kassan->Billmate Bankbetalning->Titel.

https://www.dropbox.com/s/mohlpirb6tm6uz7/Selection_00103.jpg?dl=0

**Comment by ben72** [comment]
Since then it's only been "Billmate Bankbetalning". So it looks like the title setting is not respected. Not sure it should, maybe it should only be used for the customer in the checkout like it says. But it was strange that both were used on the order screen like in my original screenshot!

**Comment by kalorifri** [comment]
Thank you for the information. A fix for this will be included in next release.

**Comment by andyjohansson** [comment]
This issue is now solved in the latest release.
