### ISSUE TITLE
Possible to make social security number / organization number required?

### ISSUE THREAD

**Issue by Yodapp** [Billmate/woocommerce#244]
Is it possible to make "person nummer / org. nummer" required?

If not, is that something you could consider as an option? I could make a pull request in that case.

**Comment by andyjohansson** [comment]
Hi @Yodapp, in what context are you talking? 
Do you want to make the "Fetch adress" functionality mandatory in the standard payment methods?
Or are you talking about Billmate Checkout?

**Comment by ben72** [comment]
@Yodapp Can't you do this in the hook woocommerce_checkout_process where needed?

**Comment by Yodapp** [comment]
@ben72 Thanks, sometimes the most obvious solution is the last that comes to mind. :-)

@andyjohansson I think this issue is resolved. Thanks anyway! 👍

**Comment by andyjohansson** [comment]
Sounds great 🍡
