### ISSUE TITLE
Fatal errors

### ISSUE THREAD

**Issue by ben72** [Billmate/woocommerce#254]
I found this in the logs and it's repeated on multiple days..

2018-09-14T09:00:03+00:00 CRITICAL Uncaught Exception: Felaktig order: in /home/ekoinsik/public_html/lotuseco/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:100
Stack trace:
#0 /home/ekoinsik/public_html/lotuseco/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(156): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order))
#1 /home/ekoinsik/public_html/lotuseco/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(111): WC_Data_Store->read(Object(WC_Order))
#2 /home/ekoinsik/public_html/lotuseco/wp-content/plugins/billmate-payment-gateway-for-woocommerce/gateway-billmate.php(524): WC_Abstract_Order->__construct('7310')
#3 /home/ekoinsik/public_html/lotuseco/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-bankpay.php(132): WC_Gateway_Billmate->common_check_ipn_response(Array)
#4 /home/ekoinsik/public_html/lotuseco/wp-includes/class-wp-hook.php(286): WC_Gateway_Billmate_Bankpay->check_ipn_response('')
#5 /home/ekoinsik/public_html/lotuseco/wp-in

**Comment by andyjohansson** [comment]
Closing due to old issue. Please open up again if it is still applicable.

**Comment by jackbillstrom** [comment]
Encountered the same problem in a clients project. It's being caused when a user has fulfilled the `iframe` checkout and redirects the browser towards `/checkout?wc-api=WC_Gateway_Billmate_Checkout&payment=success&method=checkout`. 

However we managed to make successful orders yesterday after disabled a plugin which was conflicting (AeroCheckout).

If back my browser from `/checkout?wc-api=WC_Gatewa....` to `/checkout` I can see that Billmate is showing a reciept of my order. No order got saved in WooCommerce tho.


WooCommerce version: 4.5.2
Billmate Payment Gateway for WooCommerce: 3.11.2
WooCommerce Services: 1.24.3

❗ **Fatal error**: Uncaught Exception: Felaktig beställning:
in **/var/www/swepos/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php** on line 105

Callstack:

    Abstract_WC_Order_Data_Store_CPT::read()
    wp-content/plugins/woocommerce/includes/class-wc-data-store.php:159
    WC_Data_Store::read()
    wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php:112
    WC_Abstract_Order::__construct()
    wp-content/plugins/billmate-payment-gateway-for-woocommerce/gateway-billmate.php:563
    WC_Gateway_Billmate::common_check_ipn_response()
    wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-checkout.php:1195
    WC_Gateway_Billmate_Checkout::check_ipn_response()
    wp-includes/class-wp-hook.php:287
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:311
    WP_Hook::do_action()
    wp-includes/plugin.php:478
    do_action()
    wp-content/plugins/woocommerce/includes/class-wc-api.php:161
    WC_API::handle_api_requests()
    wp-includes/class-wp-hook.php:287
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:311
    WP_Hook::do_action()
    wp-includes/plugin.php:544
    do_action_ref_array()
    wp-includes/class-wp.php:388
    WP::parse_request()
    wp-includes/class-wp.php:745
    WP::main()
    wp-includes/functions.php:1285
    wp()
    wp-blog-header.php:16
    require()
    index.php:17
