### ISSUE TITLE
Remove html code from product titles on invoices

### ISSUE THREAD

**Issue by ben72** [Billmate/woocommerce#264]
On the invoice I get `&amp;` in product titles instead of `&`. 

Screenshot of a part of an invoice:
![invoice](https://user-images.githubusercontent.com/1370224/51090162-ff1abc00-1777-11e9-8e5c-41f8ea23eab5.png)

I think you should use something like `html_entity_decode` on product titles.

**Comment by ben72** [comment]
Thanks! I think you fixed this in #265

**Comment by kalorifri** [comment]
Hi!
It is now fixed and released, version 3.4.3
