### ISSUE TITLE
Missing orders in WooCommerce with Swish!

### ISSUE THREAD

**Issue by ben72** [Billmate/woocommerce#267]
Swish order set to status "Utbetald" in Billmate but no order created in WooCommerce! This has happened multiple times 20/2-26/2. The order numbers in WooCommerce are increased when this happens but no order is visible. This does not happen all the time..

**Comment by stefanliden** [comment]
Hello Ben. Please write an email to us on support@billmate.se. Please write to us which customers it concerns and their invoice number and order number. If you have other information in the log please post it here so we can see it directly.

**Comment by ben72** [comment]
@stefanliden Thanks, will do!
