### ISSUE TITLE
Check if Pclasses Exists when showing Part payment in frontend

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/woocommerce#28]
Check if Pclasses Exists when showing Part payment in frontend

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by Boxedsolutions** [comment]
Tell me when you want to test this feature as i need to manually drop paymentplans in database

**Comment by joakim-combain** [comment]
Is this for product level? Or where in frontend are we talking?

**Comment by Boxedsolutions** [comment]
It shouldnt be visible anywhere i Guess, when no paymentplans exists

**Comment by joakim-combain** [comment]
Ok. Could you please drop it now so I can test it?

**Comment by Boxedsolutions** [comment]
It should now be dropped in both sites

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
