### ISSUE TITLE
Hit area too small for accepting Billmate billing for mobile

### ISSUE THREAD

**Issue by ben72** [Billmate/woocommerce#280]
Steps to reproduce:
1. Go to checkout on a mobile
2. Try to tick the checkbox for "Min e-post är korrekt och får användas för fakturering.."

Normally I have to try 4-5 times before I can check it if I don't zoom in on it.
This is not acceptable as >50% of traffic comes from mobiles now!

Try clicking the checkbox for accepting store terms in WooCommerce. The hit area includes the whole paragraph which makes it much easier to check the box. Please do the same for this checkbox.

Since the checkbox is no longer ticked by default we've seen a significant drop in orders and especially with invoice as payment alternative. So it's important that the checkbox is at least easy to tick!

**Comment by stefanliden** [comment]
Thank you Ben,
We will look further at how we can create an improvement on the confirmation box.

**Comment by stefanliden** [comment]
This is resolved and works in 3.4.9

**Comment by ben72** [comment]
This can make a huge difference in sales. Thanks for fixing it!

**Comment by ben72** [comment]
@stefanliden This was reverted in 3.4.10. Please fix it again! Also check if other fixes were reverted by mistake in 3.4.10.
