### ISSUE TITLE
Loopbacks blocked

### ISSUE THREAD

**Issue by ben72** [Billmate/woocommerce#286]
Whenever both WooCommerce and WooCommerce Billmate Gateway is installed this happened. I've tested on a vanilla install with nothing else and it's the same as on my dev and live sites.

To reproduce:
1. Install WordPress
2. Install and activate WooCommerce
3. Install and activate WooCommerce Billmate Gateway
4. Check Tools->Site Health

There are two critical errors:
The REST API encountered an error
Your site could not complete a loopback request

The issue for me is that it blocks loopback which is used by certain plugins which now does not work properly. For example Backupbuddy Stash Live function and probably also Mailchimp for WooCommerce which can't sync to Mailchimp!

![Image of error in Health Check](https://bentrix.com/downloads/public/billmate-rest-api-error.png)

**Comment by stefanliden** [comment]
Thank you Ben,
We will look into this further.

**Comment by ben72** [comment]
I have found this to be an issue on another client site as well and it's located on another server.

**Comment by ben72** [comment]
I can confirm this is fixed by #292 
Thank you @henrik-lofstrom

**Comment by ben72** [comment]
This is a problem in 3.6.1 again!!
It stops for instance Mailchimp for WooCommerce sync. :(

**Comment by ben72** [comment]
Applying the fix in #292 to 3.6.1 fixes the issue. Please apply that fix and don't loose it again on those revert actions! :)

**Comment by stefanliden** [comment]
Hello Ben,

We had to do this revert at this fix. The created more problems are useful. We will release a better fix for the problem. I'll be back as soon as I have more information.

If you have any other questions please do not hesitate to contact us at billmate@support.se

**Comment by ben72** [comment]
@stefanliden OK, what kind of problems? It works for me. Mailchimp for WooCommerce can sync, it can't without the change.

**Comment by ben72** [comment]
Isn't it time to get this fixed now?

The WordPress Site Health Status still shows 2 critical issues due to your plugin!
The REST API encountered an error
Your site could not complete a loopback request

With this error for example the sync for Mailchimp for WooCommerce does not work! The change you made before but reverted works fine here. What issues have you seen with it?
Every time I update the plugin I have to patch the code to fix this.
Please fix asap!

**Comment by ben72** [comment]
@MattiasNilsson 
I can confirm that this is still an issue in 3.10.3. And that it's fixed by #292. Can you please fix this asap so we don't have to patch the code for every update!

The Billmate for WooCommerce plugin currently causes 2 fatal errors i WordPress Site Health Status!
Tools->Site Health (which is default in every WP install)

**Comment by MattiasNilsson** [comment]
@ben72 We are looking into it!

**Comment by ben72** [comment]
@MattiasNilsson Any progress on this one?

**Comment by MattiasNilsson** [comment]
@ben72 We are still looking into it as this a bit tricky and we focus on finding the main problem. We keep you posted.

**Comment by ben72** [comment]
This is not fixed! Still. After more than a year.. :-1:
