### ISSUE TITLE
Properly replace old Bilmate logo with new one

### ISSUE THREAD

**Issue by ben72** [Billmate/woocommerce#287]
The new logo was added in one of the latest commits but it was in jpg format and in the code png files are used.

On a side note, shouldn't it be png with transparent background like the old one? And you should remove the old images. And you need to update the Readme.txt about using your logo, including links to the old logo.

**Comment by stefanliden** [comment]
Thank you Ben,

We look at this and come back with answers. If you have more questions, you are always welcome to email support@billmate.se

**Comment by ben72** [comment]
@stefanliden Sounds great! Since you added the new logo I've patched the code locally to display the new logo in the checkout. :)

**Comment by stefanliden** [comment]
This is resolved and works in 3.4.9
