### ISSUE TITLE
If you enter a matching adress it still shows billmatepopup

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#29]

**Comment by Boxedsolutions** [comment]
Should be solved now

**Comment by andyjohansson** [comment]
This one was I talking about @joakim-combain. I'm testing it now.

**Comment by joakim-combain** [comment]
Ok, is it fixed? Does this plugin need more testing from my part?

**Comment by andyjohansson** [comment]
Test everything again @joakim-combain, all should be fixed now with the correct branch from master.

**Comment by andyjohansson** [comment]
To test part payment you have to get the pclasses again.

**Comment by joakim-combain** [comment]
Can't access the page http://wp-4-0-wc-2-2-6.andyjohansson.com.preview.citynetwork.se/

**Comment by andyjohansson** [comment]
I have no trouble accessing it... Screenshot?

**Comment by andyjohansson** [comment]
I can access the page without problems. And I tested this issue and it´s closed.
