### ISSUE TITLE
 Notice: Undefined variable: imgHtml in commonfunctions.php on line 1846

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/woocommerce#293]
imgHtml on line 1846 (file commonfunctions.php) is undefined and leaves a notice in the admin backend.

<img width="870" alt="Skärmavbild 2019-08-10 kl  20 04 00" src="https://user-images.githubusercontent.com/1516103/62825319-0f7a0480-bbaa-11e9-9605-933146742d97.png">

**Comment by stefanliden** [comment]
Thank you Daniel,

We look at this and come back with answers. If you have more questions, you are always welcome to email support@billmate.se

**Comment by stefanliden** [comment]
This is resolved in V3.4.9
