### ISSUE TITLE
Order is created before it's a order (old API)

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#30]
When you enter a social security number which is not approved an order is created in the back-end (tested for Invoice). Do we need to create orders?

**Comment by Boxedsolutions** [comment]
We need to discuss this part as we make the creditcheck when the order is created in the process_payment method. 

I have moved the address verification to validate_fields method, but it seems not right to do the creditcheck that early in the process either.

**Comment by andyjohansson** [comment]
So what´s the status on this one for now?

**Comment by Boxedsolutions** [comment]
I will try to explain the issue with this when we meet up in Your Head Quarter. I think its easier to explain with the code and an explanation on what is happening

**Comment by andyjohansson** [comment]
Implement as we discussed over the phone @Boxedsolutions

**Comment by Boxedsolutions** [comment]
I have done a check in the WooCommerce core, It might be possible, but it must be a better way. I will research a better approach to make this as smooth as possible.

**Comment by Boxedsolutions** [comment]
The risk of crash some module that hook checkout events makes this not solvable in a good way
