### ISSUE TITLE
Warning: Illegal string offset 

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/woocommerce#307]
I'm getting some warnings on the checkout page when loading Billmate Checkout. Version 3.4.9, WooCommerce 3.7.0. A minor issue.

( ! ) Warning: Illegal string offset 'description' in /var/www/web/app/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-account.php on line 606

( ! ) Warning: Illegal string offset 'minamount' in /var/www/web/app/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-account.php on line 608

( ! ) Warning: Illegal string offset 'maxamount' in /var/www/web/app/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-account.php on line 608

**Comment by stefanliden** [comment]
Thanks Daniel, 

I have reported this problem and we will look at a solution. If you have any other questions, you are always welcome to contact support@billmate.se
