### ISSUE TITLE
Problems with orders containing multiple order rows with the same articleid

### ISSUE THREAD

**Issue by perfectsenseab** [Billmate/woocommerce#308]
In the latest version of the Billmate Woocommerce plugin (3.4.9) an issue was introduced that you no longer accept an order to contain multiple order rows with the same articleid. This has been working perfectly for the last 5 years and i don't see any reason at all why this should be limited now. WooCommerce supports this and your own API supports this so why limit this in your WooCommerce plugin? Here is the offending commit:

https://github.com/Billmate/woocommerce/commit/e91903fee8b05af77caacc221640de6ede403d58#diff-5a2cdec7846c4c75856b8cb2c0ff6adc

Please revert to the old code as soon as possible because this is causing big problems for us.

**Comment by DanielMarklund** [comment]
Experiencing this issue as well on my local setup. This makes some instances of grouped products where one product is added in multiple groups. It also makes some cross sell plugins incompatible with Billmate, as one product can show up multiple times in an order (with or without different prices).

**Comment by stefanliden** [comment]
Thanks,

We at Billmate have now chosen to revert to version 3.4.7 after these problems. As we release the new version of Billmate, we will look at how we can solve these problems.

If you have more questions, please contact support@billlmate.se

**Comment by ben72** [comment]
Did you revert just this change or all changes? It's pretty vague what you did in the changelog..

**Comment by MattiasNilsson** [comment]
Old ticket closing.
