### ISSUE TITLE
I got these error messages in checkout page.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#33]
Notice: Undefined index: billmate_invo_pno in /storage/content/17/102017/wp-4-0-wc-2-2-6.andyjohansson.com/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-invoice.php on line 1193

Notice: Undefined index: maxtotal in /storage/content/17/102017/wp-4-0-wc-2-2-6.andyjohansson.com/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 393 Notice: Undefined index: maxtotal in /storage/content/17/102017/wp-4-0-wc-2-2-6.andyjohansson.com/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 393

![checkout wordpress 4 0 woocommerce 2 2 6](https://cloud.githubusercontent.com/assets/10434920/5973701/aec492e6-a86b-11e4-8782-c28769e3d1fc.png)

**Comment by Boxedsolutions** [comment]
The last error is for Paymentplans is not refreshed as the old payment plans didnt have maxtotal

**Comment by andyjohansson** [comment]
Din't we delete that file in the project fils so this shouldn't occur?
Can't we add a check so if it´s not correct we disable it @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Of some Reason the file is in the repo. It should be killed. Did you upload the latest commits? As this would solve the rest issues with undefined payment_method

**Comment by andyjohansson** [comment]
Test again @joakim-combain.
