### ISSUE TITLE
I got these error messages after entering 5505050558 in invoice.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#34]
Notice: Undefined index: maxtotal in /storage/content/17/102017/wp-4-0-wc-2-2-6.andyjohansson.com/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 393 Notice: Undefined index: maxtotal in /storage/content/17/102017/wp-4-0-wc-2-2-6.andyjohansson.com/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 393 Notice: Use of undefined constant WPLANG - assumed 'WPLANG' in /storage/content/17/102017/wp-4-0-wc-2-2-6.andyjohansson.com/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-invoice.php on line 851 Notice: Undefined index: se in /storage/content/17/102017/wp-4-0-wc-2-2-6.andyjohansson.com/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-invoice.php on line 852 Strict Standards: Non-static method BillmateCountry::getSwedenData() should not be called statically, assuming $this from incompatible context in /storage/content/17/102017/wp-4-0-wc-2-2-6.andyjohansson.com/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-invoice.php on line 871

Notice: Undefined index: maxtotal in /storage/content/17/102017/wp-4-0-wc-2-2-6.andyjohansson.com/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 393 Notice: Undefined index: maxtotal in /storage/content/17/102017/wp-4-0-wc-2-2-6.andyjohansson.com/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 393 Notice: Use of undefined constant WPLANG - assumed 'WPLANG' in /storage/content/17/102017/wp-4-0-wc-2-2-6.andyjohansson.com/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-invoice.php on line 851 Notice: Undefined index: se in /storage/content/17/102017/wp-4-0-wc-2-2-6.andyjohansson.com/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-invoice.php on line 852

![checkout wordpress 4 0 woocommerce 2 2 62](https://cloud.githubusercontent.com/assets/10434920/5973748/3e86fd38-a86c-11e4-9a77-d8c6a8a2d03e.png)

**Comment by andyjohansson** [comment]
These issues are related to wrong branching. @Boxedsolutions will fix this ASAP.
