### ISSUE TITLE
Error on checkout if you create an account when you checkout

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#35]
Look at this video to see the issue: https://v.usetapes.com/IUWOUwwkcu
When I try to recreate it on the test store I don´t get the error: https://v.usetapes.com/ggDtClTkba

The error can be seen here in the console:
![skarmavbild 2015-01-30 kl 18 03 16](https://cloud.githubusercontent.com/assets/4968755/5979845/851acc72-a8ab-11e4-88f3-880611ac6908.png)

Here are the JS files both in minimized and in non minimzed version:
http://cl.ly/code/432N021g1s37
http://cl.ly/code/1l2T0x031q0Q

The site now has the latest version, no difference.

**Comment by joakim-combain** [comment]
This seems to work. But I found something weird but don't know if it's our plugin issue or issue with woocommerce.

If I while in the checkout choose to create an account and then choose invoice as payment method. I put 5505050558 and get error message. Now I choose Card and after it has loaded it says -1 and I have no payment options anymore.

**Comment by Boxedsolutions** [comment]
Will check what the cause of this is.

**Comment by andyjohansson** [comment]
Any updates here?

**Comment by Boxedsolutions** [comment]
I need to work it out a way to fix this. The error is that the Order is created someway.

**Comment by andyjohansson** [comment]
Make sure this is now included in 2.0 @Boxedsolutions.

**Comment by Boxedsolutions** [comment]
Its implemented in the same way as earlier version

**Comment by joakim-combain** [comment]
This seems to be working. Can't see any issues. Closing it.
