### ISSUE TITLE
URGENT ISSUE - Vat is wrong when using card.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#37]
We need to fix this asap and release new version!

Invoice number: 6961
Order number: 141
Opencart BO account.

@Boxedsolutions @andyjohansson

**Comment by andyjohansson** [comment]
Which version and what store have you tested in?

**Comment by andyjohansson** [comment]
I found it, we are looking into it.

**Comment by Boxedsolutions** [comment]
Test again Configuration issue with VAT classes. If there are multiple VAT rates under the same VAT class and no country restrictions the rates will compund, So that 12% +25% becomes 37%

I Made a Change and separated them and now it seems to work.

**Comment by andyjohansson** [comment]
@joakim-combain please verify this.

**Comment by andyjohansson** [comment]
Is this and #35 pushed to the test site @Boxedsolutions? If so please test and verify #35 as well @joakim-combain and then we can make a release.

**Comment by Boxedsolutions** [comment]
By the way, I set Testproduct to 12% VAT :) TestProduct åäö to 25% To be able to test different vat rates

**Comment by joakim-combain** [comment]
I tested this now and it seems to work. Closing it.
