### ISSUE TITLE
Check so that you can check out correctly with another currency than SEK

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#38]
Invoice:
Test to checkout with other currency than SEK. Should be that currency in all declarations of the order.
Card:
Test to checkout with other currency than SEK. Should be that currency in all declarations of the order.

Also check so that the Invoice fee is displayed and handled correctly. It should be converted to the currency used in the checkout process.

**Comment by Boxedsolutions** [comment]
It seems to send the right currency when i Changed the store currency

**Comment by andyjohansson** [comment]
This works correct also with the invoice fee @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Yes as far as I tested it. As i said I changed the store currency. I will research if any plugin makes it available to choose currency in frontend. But i think it should work anyway.

**Comment by joakim-combain** [comment]
Bank seems to be deactivated when I change to EUR currency. Should it be like this?

**Comment by andyjohansson** [comment]
Yes, bank and part payment is only allowed with SEK as currency. Card and invoice should only work. Can we close this @joakim-combain?

**Comment by joakim-combain** [comment]
Then we should be able to close these, yes. Closing the issue.
