### ISSUE TITLE
Notice: get_used_coupons deprecated since version 3.7! Use WC_Abstract_Order::get_coupon_codes instead.

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/woocommerce#383]
**Notice about deprecated function:**
WC_Order->get_used_coupons( ) in commonfunctions.php:1756
Use WC_Abstract_Order::get_coupon_codes() instead.

**Comment by DanielMarklund** [comment]
This notice breaks the page on dev environments if debugging is enabled, when trying to remove an item from cart. **Warning: Cannot modify header information - headers already sent.** Nothing renders after the warning appears.

## Workaround

### Before:
$coupons = $this->order->get_used_coupons();

### After:
$coupons = $this->order->get_coupon_codes();

**Comment by stefanliden** [comment]
Hi Daniel,

We have fixed this notice and in the code change has been added in version 3.9.7.
