### ISSUE TITLE
Notice: Undefined index: billmate_checkout_mode in class-billmate-checkout.php on line 954

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/woocommerce#389]
Notice: Undefined index: billmate_checkout_mode in /home/woouser/wordpress_staging/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-checkout.php on line 954

**Comment by stefanliden** [comment]
Thanks Daniel, 

We haven't looked into this yet, but we will verify this issue from our site and come back with more information about the issue.

**Comment by andyjohansson** [comment]
We are currently in the last step to close this issue.

**Comment by stefanliden** [comment]
Hi @DanielMarklund 

We have now fixed this and the fix is ​​in production. If you have any questions about this or other considerations, you are always welcome to contact us again 💯
