### ISSUE TITLE
Order is created when billmatepopup is triggerd

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#39]
The order should not be created until its a valid order.

Client reported this with: 1.35.1

**Comment by andyjohansson** [comment]
Make sure this is in the 2.0 release @Boxedsolutions.

**Comment by Boxedsolutions** [comment]
It should not create a order now just for billmatepopup, that function is moved to a different place.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
