### ISSUE TITLE
Billmate Checkout refreshes page on any price/shipping change

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/woocommerce#396]
I've had problems with the checkout page refreshing on cart/shipping change when Billmate Checkout is enabled. Not sure why it behaves like this, if it's intended or if it's a bug. I've attached a workaround that works for me.

**Expected behaviour:**

1. Customer changes shipping method.
2. The order review refreshes via AJAX.
3. Billmate Checkout iframe refreshes.

**Current behaviour:**

1. Customer changes shipping method.
2. The order review refreshes via AJAX.
3. Billmate Checkout iframe refreshes.
4. Billmate Checkout iframe starts to refresh once again.
5. The whole checkout page refreshes.

## The workaround

**js/billmatecheckout.js: Line 54**

### Before:
```
if (response.hasOwnProperty("data") && response.data.hasOwnProperty("order_total")) {
    if (self.orderTotal != undefined && self.orderTotal != response.data.order_total) {
        self.lock();
        location.reload(true);
        return true;
    }
    self.orderTotal = response.data.order_total;
}
```

### After:
```
if (response.hasOwnProperty("data") && response.data.hasOwnProperty("order_total")) {
    if (response.data.hasOwnProperty("update_checkout") && response.data.update_checkout) {
        self.lock();
        location.reload(true);
        return true;
    }
    if (self.orderTotal != undefined && self.orderTotal != response.data.order_total) {
      self.orderTotal = response.data.order_total;
    }
}
```

**Comment by MattiasNilsson** [comment]
Hi @DanielMarklund 

This issue have now been adressed and this is a setup requirement that now needs to be fulfilled. A documentation part can be found here:
https://github.com/Billmate/woocommerce/pull/442

See section 7.

> Go to --> WooCommerce --> Settings --> General --> Default Customer Location and set it to any setting except 'No location by default'
