### ISSUE TITLE
Missing payment method title

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/woocommerce#398]
I've already reported to Billmate AB, but I'll make an issue here as well to hopefully escalate it a bit more. Sometimes orders don't have info about which payment method was used, only "Billmate Checkout". This seems to happen mostly to Swish orders. This gives external business systems trouble as some of them assign payment methods based on the method title.

**Swish order with missing title:**
Meta Key | Meta Value
_payment_method_title | Billmate Checkout
 
**Swish order that has a correct title:**
Meta Key | Meta Value
_payment_method_title | Billmate Checkout (Swish)

Searching for an order that has a missing payment method via https://developer.billmate.se/api-integration/getpaymentinfo/ shows that the following info is not added:

```
"data": {
        "PaymentData": {
            [..]
            "method_name": "Swish",
```

I thought https://github.com/Billmate/woocommerce/pull/327 was going to solve this issue, but when using the current version this issue still remains.

For test cases (order ID's that are affected by the bugs), please let me know via e-mail (we have a conversation open).

**Comment by stefanliden** [comment]
Thanks Daniel,

We will review this issue and come back with more informaton.

If you have any other questions, you are always welcome to contact us at support@billmate.se

**Comment by DanielMarklund** [comment]
Thank you. Do you have any ETA on when this is solved? The ERP we use can't understand which payment method has been used for these orders, so their staff have to activate them manually which they debit us for (as the issue is with Billmate and not them). It's getting expensive...

**Comment by andyjohansson** [comment]
We are prioritizing a fix for this at the moment @DanielMarklund

**Comment by DanielMarklund** [comment]
Got any updates on this issue? @andyjohansson @stefanliden <3

**Comment by stefanliden** [comment]
Hi Danielm,

The status right now is that we are actively working to resolve this issue. We will of course return to you again when we have new information 👍

**Comment by stefanliden** [comment]
Hi @DanielMarklund ,

Now we have created a new version to prevent this problem from occurring again. If you update to V3.9.14 you will have the code change with the new solution.

Thank you for the issue reporting and feel free to contact us if you have any questions to support@billmate.se

**Comment by DanielMarklund** [comment]
Thank you. I've had this active for 24 hours now and no issues so far. Will let you know if this happens again.
