### ISSUE TITLE
Tax Issue with Dynamic Pricing

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/woocommerce#40]
Some strange behaviour when calculating tax from item tax and item total

**Comment by Boxedsolutions** [comment]
Did a rewrite so we use the TaxClass on the product instead of manually calculate the rate. Should work

**Comment by andyjohansson** [comment]
Make sure this is included in the 2.0 release @Boxedsolutions.

**Comment by Boxedsolutions** [comment]
Its Implemented. Where do we have this module so I can put it up
