### ISSUE TITLE
Don´t display this error message if eid and secret is not filled

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#42]
![skarmavbild 2015-03-06 kl 14 21 03](https://cloud.githubusercontent.com/assets/4968755/6525946/56a9def6-c40c-11e4-92da-134e9e1fb895.png)

**Comment by andyjohansson** [comment]
Make sure this is included in the 2.0 release @Boxedsolutions.

**Comment by Boxedsolutions** [comment]
It should be implemented.

**Comment by joakim-combain** [comment]
The error message coming now if you leave key and billmate id empty is in english. Needs to be translated, otherwise it is fixed.

**Comment by Boxedsolutions** [comment]
It should now be translated

**Comment by joakim-combain** [comment]
Still says "Please, check your credentials". I'm testing in incognito so shouldn't be any cache issue on my side.

**Comment by Boxedsolutions** [comment]
It should be translated now

**Comment by joakim-combain** [comment]
There is an issue now where I can save 727 as billmate ID. This should result in an error message.

**Comment by Boxedsolutions** [comment]
It should be fixed now. As the api return 9012 for 727 so I have added this error code

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
