### ISSUE TITLE
3.9 - I found an issue where part payment isn't loading at all in checkout.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#43]
![checkout wp 3 9 testarea](https://cloud.githubusercontent.com/assets/10434920/6776131/02b9b460-d13b-11e4-9a92-ca1e35481853.png)

I have checked everything that could be wrong for example, available country and minimum and maximum thresholds. Nothing solves it.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
This is fixed. Closing the issue.
