### ISSUE TITLE
3.9 - You are sending autoactivate 1 in bank orders. There should be a setting like card for this.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#44]
apilogsid: 11137
invoice number: 209937

**Comment by Boxedsolutions** [comment]
Will fix this tonight.

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
![woocommerce remove comma sign](https://cloud.githubusercontent.com/assets/10434920/6820348/56f22546-d2ce-11e4-925a-54f768bb3352.png)

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
