### ISSUE TITLE
3.9 - All of our plugins should have Sweden selected by default when installing the plugin. Today you have to choose allowed country.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#45]

**Comment by Boxedsolutions** [comment]
Now have I implemented default country Sweden

**Comment by joakim-combain** [comment]
We need to remove Allowed countries for all plugins and just have hard coded allowed countries.

All countries for Card

Bank, Part pay and Invoice should only be available for Sweden right now. Later on we can expand the hard coded countries when we accept them.

![woocommerce remove allowed countries](https://cloud.githubusercontent.com/assets/10434920/6864622/7ead5672-d464-11e4-815c-dd07887e13a3.png)

**Comment by andyjohansson** [comment]
Me and @Boxedsolutions  have discussed this now over the phone and we will implement the following:
Allowed countries will be available as an option for all payment methods.
Bank, Partpay & Invoice will have Sweden as the only allowed country and will default to that.
Card will have none selected by default and if nothing is selected all countries are allowed.

**Comment by Boxedsolutions** [comment]
Changed the available countries for partpay, bankpay and invoice and added all countries for cardpay

**Comment by joakim-combain** [comment]
But why do we have this option at all if only Sweden should be allowed for all but Card? Is there any logical explanation for this? I mean, as a customer, it would be strange if I have the option to put Norway as an allowed countries and then it doesn't work. Or am I misunderstanding?

**Comment by andyjohansson** [comment]
You are correct @joakim-combain. Me and @Boxedsolutions will discuss this when we get together this week.

**Comment by Boxedsolutions** [comment]
Changed the logic for the allowed countries

**Comment by joakim-combain** [comment]
I can still choose norway for Invoice and part pay. Card is missing this option altogether, shouldn't the customer be able to choose allowed countries? I mean, if the customer only wants to allow orders from sweden or from nordic countries they should have the option to do so.

**Comment by joakim-combain** [comment]
Bank still have Allowed countries option. Remove that option and then it should be fine.

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
