### ISSUE TITLE
Change wording on fail due to address

### ISSUE THREAD

**Issue by ben72** [Billmate/woocommerce#450]
When the customer tries to use an incorrect delivery address you get a dialog saying this at the end:
"Nej jag vill ändra till ett annat nummer eller byta betalmetod". What is "nummer"?? It should say "personnummer"?

Also, it's not obvious that you can click on that text. I got this comment from a customer: "Det gick inte att ändra orden när man väl tryckt på slutför köp". Maybe it should be a gray button.

![image](https://user-images.githubusercontent.com/1370224/83968762-aba89100-a8cb-11ea-916b-bc6514ec850d.png)

**Comment by MattiasNilsson** [comment]
@ben72 Thanks for the feedback! We are going to take a look at it.

**Comment by ben72** [comment]
@MattiasNilsson Kan ni kolla mina förslag i  #455??

**Comment by MattiasNilsson** [comment]
This is now fixed in #455
