### ISSUE TITLE
Critical error in version 3.10.12

### ISSUE THREAD

**Issue by perfectsenseab** [Billmate/woocommerce#451]
There is a critical error in the latest version of the Billmate plugin preventing customers from completing a creditcard payment:

PHP Fatal error:  Uncaught Error: Call to a member function is_taxable() on null in /wp-content/plugins/billmate-payment-gateway-for-woocommerce/gateway-billmate.php:1316

I had to revert back to 3.10.11 to get it creditcard payments working again.

**Comment by MattiasNilsson** [comment]
@perfectsenseab A new release have been made which fixes this error: https://github.com/Billmate/woocommerce/releases/tag/3.10.13
