### ISSUE TITLE
Catastrophic update 3.10.18

### ISSUE THREAD

**Issue by perfectsenseab** [Billmate/woocommerce#458]
The latest version 3.10.18 of the plugin introduced an artificial limitation that prevents customers from ordering products with the same SKU. This causes alot of problems for us as our customers depend on this feature of WooCommerce. There has not been a need for this artificial limitation of the Billmate plugin for 6 years.

**Comment by MattiasNilsson** [comment]
This was fixed with the 3.10.19 release: https://github.com/Billmate/woocommerce/releases/tag/3.10.19
