### ISSUE TITLE
3.9 - The text for invoice fee needs to be changed.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#46]
It says "Add a invoice fee cost without vat, leave empty to disable" should be "Add an invoice fee cost without vat, leave empty to disable."

There is a grammar issue in the text we have now.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
This needs to be translated aswell.

![woocommerce translation issue](https://cloud.githubusercontent.com/assets/10434920/6820299/d8dc9b00-d2cd-11e4-9ba1-5068a331994e.png)

**Comment by Boxedsolutions** [comment]
It should be fixed now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
