### ISSUE TITLE
CRITICAL: ÅÄÖ is not saved/rendered correctly – unable to send orders!

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/woocommerce#467]
Not sure if it's on your side or on UC (if that's the registry you use), but orders from Friday to this morning containing åäö has the wrong encoding. As many of us use another business systems for handling shipments etc, all the data is also wrong there now. It's also not possible to edit the order details in Billmate Online.

We can't send any orders until this is resolved, so this is super critical.

This issue is also confirmed by @ben72 (thanks for letting us know).

**Comment by MattiasNilsson** [comment]
Hi @DanielMarklund and @ben72, we have had this issue during the weekend and it is now fixed in our Checkout. It was not related to the WooCommerce module.

Thanks for your patience and understanding!

**Comment by DanielMarklund** [comment]
Hi @MattiasNilsson, thank you for the swift response.

Will you make corrections to all the orders in Billmate Online, so the invoice details etc will be correct?

**Comment by ben72** [comment]
Thank you. I can confirm it's now working.
