### ISSUE TITLE
3.9 - It seems like some discount types are not accounted for in our billmate invoices.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#47]
There are now 4 discount codes. 2 of them are noted in the billmate invoice and 2 are not.

test123 - accounted for in 7238 (order id 22)
teståäö - is not accounted for in 7239 (order id 23)
123åäö - is accounted for in 7240 (order id 24)
åäö123 - is not accounted for in 7241 (order id 25)

**Comment by Boxedsolutions** [comment]
teståäö and åäö123 seems to subtract from the item price? We need to implement a strategy for that to work. 
@andyjohansson What priority is it? It may take a little time to figure out the best way. I also noticed that we probably should add the discounts per VAT.

**Comment by andyjohansson** [comment]
Is this one also fixed now @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
In what priority is it? We have to use the discount percentage on Articles to get this in a nice way. WooCommerce calculates and give us the discounted price for the product which is usually a good thing.

**Comment by andyjohansson** [comment]
Check the cart object @Boxedsolutions

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This is how it works now:

test123 is put as seperate articles
teståäö is put as discount on the articles
123åäö is put as seperate articles
åäö123 is put as discount on the articles.

Is this how it's intended to be? Or should they all be the same?

**Comment by Boxedsolutions** [comment]
ITs Impossible to get all discount codes display in the same way :( This is what i could do with the info from WooCommerce.

**Comment by Boxedsolutions** [comment]
@andyjohansson Whats your opinion here?

**Comment by andyjohansson** [comment]
I trust you @Boxedsolutions. Is the amounts correct @joakim-combain? If so, close it.

**Comment by joakim-combain** [comment]
Looks like it's working. Closing it.
