### ISSUE TITLE
3.9 - I'm getting this weird issue now when trying to check out with card and bank.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#48]
Billmate Error Code:9003. The function name is required. Make sure that you provide valid Content-Type and Content-Length in the header.

There is no apilog for this issue.

**Comment by Boxedsolutions** [comment]
I havent done anything. Did it work before?

**Comment by joakim-combain** [comment]
I'm only getting this issue in incognito window. Otherwise it works.

**Comment by Boxedsolutions** [comment]
Hmm, that makes it even more wierd. I think i will need to check it up to get an idea of what that make this issue.

**Comment by Boxedsolutions** [comment]
Tried now with incognito and it works. Might been some cache or something

**Comment by joakim-combain** [comment]
If I remember correctly this issue happens when you create an account while checking out and specifically with bank and card only. Don't remember where I said this but I know I have told you about it before.

**Comment by Boxedsolutions** [comment]
as Stated in #41 it should be fixed.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
