### ISSUE TITLE
3.9 - I found an issue with invoice fee in checkout.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#49]
If you have 19.90 as invoice fee incl. tax, you show it as 19.9 where you say An invoice fee will be added to the order.

![woocommerce invoice fee value issue](https://cloud.githubusercontent.com/assets/10434920/6777643/bb69529e-d14b-11e4-90e3-3cecb33ccbf8.png)

**Comment by Boxedsolutions** [comment]
Ahh some price formatting missing.

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This is fixed. Closing this issue.
