### ISSUE TITLE
3.9 - It seems like I can't change language settings. Don't know if you need some plugin to do it.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#50]
Could you please check this and see if you can fix so this store is in swedish instead?

**Comment by Boxedsolutions** [comment]
I can see if I find any translation files. The good thing is that 4.1 is in Swedish.

**Comment by Boxedsolutions** [comment]
There you have the admin translated to Swedish and some of the frontend

**Comment by joakim-combain** [comment]
I need the store to be fully in swedish to test translations like error messages and such.

**Comment by Boxedsolutions** [comment]
@andyjohansson Wordpress guru help here, I have sett the wp_lang sv_SE and uploaded translation files. What is more needed?

**Comment by joakim-combain** [comment]
I actually found it. WooCommerce > System status > Tools and Translations update and press the button to force it to update.

**Comment by andyjohansson** [comment]
Do I need to do anything then?

**Comment by andyjohansson** [comment]
Ping @joakim-combain.

**Comment by joakim-combain** [comment]
Nope. This issue should be fixed. Closing it.
