### ISSUE TITLE
3.9 - There is an issue with fetching my person information. I get wrong encoded characters.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#51]
![checkout wp 3 9 testarea2](https://cloud.githubusercontent.com/assets/10434920/6778532/aa3bcd96-d153-11e4-8b48-0aae73fdf4e4.png)

9011203016

**Comment by Boxedsolutions** [comment]
Should be solved now

**Comment by joakim-combain** [comment]
This is fixed. Closing ths issue.
