### ISSUE TITLE
3.9 - There is something weird going on with address check or caching.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#52]
Now that I try to make an order with invoice with 550101101 to generate an error message that the person number is too short I get a address popup saying the name I have given in first name and last name in registration but no address. If I accept it, only first name last name is put in and rest of the fields are cleaned and I get errors that address fields needs to be put in. I get same error even if I leave the field empty and even uncheck the email checkbox.

![woocommerce popup issue](https://cloud.githubusercontent.com/assets/10434920/6779927/f39f01da-d160-11e4-9c6f-7e060db34001.png)

**Comment by Boxedsolutions** [comment]
What does the log say?

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
