### ISSUE TITLE
3.9 - If I don't put any Allowed country in settings, all countries are allowed. I changed to Chile and can order with invoice. 

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#53]
![checkout wp 3 9 testarea3](https://cloud.githubusercontent.com/assets/10434920/6780434/9176d758-d165-11e4-89e7-83d956ab1f3d.png)

Related to #45.

**Comment by Boxedsolutions** [comment]
Could you test if this was solved by issue #45

**Comment by joakim-combain** [comment]
No, this issue still needs to be fixed.

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
