### ISSUE TITLE
3.9 - Now that I put the store to swedish I have issues with putting orders with invoice.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#54]
Now when I put an order with invoice it says country doesn't match and says we are providing Sverige but Sweden is expected.

I think we fixed this for Magento or Prestashop, not sure though. Might be on our side somehow.

Apilogsid: 11239

**Comment by Boxedsolutions** [comment]
Its a common trouble, I saw some interesting in the log as the language was sv and it complaining about the country should be sweden. 

@andyjohansson could you do a quick check. In my opinion the value sent with PaymentData language should be enough.

**Comment by Boxedsolutions** [comment]
Is this fixed?

**Comment by joakim-combain** [comment]
It seems like it's fixed. I have no problems putting orders with invoice and part pay anymore. Closing this issue.
