### ISSUE TITLE
3.9 - I'm getting this strange error message in checkout.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#55]
![woocommerce error message in checkout](https://cloud.githubusercontent.com/assets/10434920/6820177/1b435bfc-d2cc-11e4-8b68-9bb7e5da8eaf.png)

**Comment by Boxedsolutions** [comment]
Should be solved by commit 9f64430

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
