### ISSUE TITLE
3.9 - I'm getting error messages in english even though store is in swedish.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#56]
![woocommerce billmate error message in english](https://cloud.githubusercontent.com/assets/10434920/6820191/42039c48-d2cc-11e4-9791-a47fc547dc6d.png)

**Comment by Boxedsolutions** [comment]
Implemented a fix just now seems to work. The only thing is the paymentplan with paymentplanid 59 that is not valid for sweden, i think

**Comment by joakim-combain** [comment]
This issue is fixed as far as I know. Closing it.
