### ISSUE TITLE
3.9 - The order status text needs to be changed.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#57]
"Väl en speciell order status för Billmate Bankbetalning, om du vill använda en egen status och inte WooCommerce inbyggda."

Needs to be changed to:

"Väl en speciell order status för Billmate Bankbetalning, om du vill använda en egen status och inte de som är inbyggda i WooCommerce." or similar.

**Comment by Boxedsolutions** [comment]
I have changed now to the text you wrote.

**Comment by joakim-combain** [comment]
Sorry, noticed an error in the text I wrote. it should be:

"Välj en speciell order status för Billmate Bankbetalning, om du vill använda en egen status och inte de som är inbyggda i WooCommerce." 

It says Väl instead of Välj right now. Although this issue is only present in Bank.

**Comment by Boxedsolutions** [comment]
I should have noticed it. But it should be fixed now

**Comment by joakim-combain** [comment]
Now we have two different descriptions for our plugins.

Part pay has: "Välj en anpassad order status för Billmate Delbetalning, om du vill använda en egen status och inte de som är inbyggda i WooCommerce."

The rest has: "Välj en speciell order status för Billmate faktura, om du vill använda en egen status och inte de som är inbyggda i WooCommerce."

Which one do we want? @andyjohansson

**Comment by Boxedsolutions** [comment]
Which do you prefer?

**Comment by Boxedsolutions** [comment]
Changed so it is like the other methods

**Comment by andyjohansson** [comment]
Can you verify @joakim-combain?

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
