### ISSUE TITLE
3.9 - I tried putting an order with part pay, but I just got error message saying No payment plans were found.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#60]
I used 5501011018 and 5505050558 to get this issue and I couldn't find an apilogsid for this issue.

**Comment by Boxedsolutions** [comment]
I guess you solved it, as I tried with partpayment now and succeeded

**Comment by joakim-combain** [comment]
Yes. It was an error on our side. Closing this issue.
