### ISSUE TITLE
3.9 - The plugins need to have default names.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#61]
If the customer leaves title empty you should have a default name to be used in checkout. This default name needs to be translated to english and swedish aswell.

![woocommerce default names](https://cloud.githubusercontent.com/assets/10434920/6824457/b62df3cc-d2f2-11e4-847f-86e38f0cf83e.png)

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
Billmate Invoice should have standard title "Billmate Faktura - Betala inom 14-dagar."

Perhaps Billmate Part pay should have standard title "Billmate Delbetalning - Betala från xx kr/mån."

**Comment by Boxedsolutions** [comment]
Should work now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
