### ISSUE TITLE
3.9 - Terms of invoice needs translation.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#62]
![woocommerce terms translation](https://cloud.githubusercontent.com/assets/10434920/6841999/a8f55d1c-d392-11e4-90fd-a875dd5143fe.png)

The text should be:

"Min e-post, joakim@combain.com, är korrekt och får användas för fakturering. Jag godkänner även köpvillkor för faktura betalning." (Punctioation missing after Terms of invoice as well)

Needs to be changed for part pay as well.

"Min e-post, joakim@combain.com, är korrekt och får användas för fakturering. Jag godkänner även köpvillkor för delbetalning."

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
I might be a bit picky now but, part payment text is missing punctuation.

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
