### ISSUE TITLE
3.9 - Explainatory text for min and max amount needs to be changed.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#63]
![woocommerce translation issue delbetalning](https://cloud.githubusercontent.com/assets/10434920/6845090/f9ec6328-d3b0-11e4-929e-c0093d03a5ce.png)

This issue is only in part pay settings.

Should be 

"Inaktivera Billmate Bankbetalning om varukorgens belopp är lägre än inställt värde. Lämna tomt för att inaktivera denna funktion." 

and 

"Inaktivera Billmate Bankbetalning om varukorgens belopp är högre än inställt värde. Lämna tomt för att inaktivera denna funktion."

**Comment by Boxedsolutions** [comment]
Damn autocorrect. @andyjohansson Is it anyway to turn of this shit in mac?

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
You need to switch them around.

"Inaktivera Billmate Delbetalning om varukorgens belopp är högre än inställt värde. Lämna blankt för att inaktivera denna funktion." This should be for max value.

"Inaktivera Billmate Delbetalning om varukorgens belopp är lägre än inställt värde. Lämna blankt för att inaktivera denna funktion." This should be for min value.

This is only for part pay as well.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
This issue is fixed. Closing this issue.
