### ISSUE TITLE
3.9 - I view one product and get a weird error message coming from our plugins.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#64]
Notice: Undefined index: eid in /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 1698

![woocommerce product issue](https://cloud.githubusercontent.com/assets/10434920/6890803/61c26570-d6b2-11e4-975e-be6471bb5209.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
I have this still.

Notice: Undefined index: eid in /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/shortcodes.php on line 27 Notice: Undefined variable: pclasses in /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/shortcodes.php on line 28
Notice: Undefined index: Type in /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 1010 Notice: Undefined index: interest in /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 1015 Notice: Undefined index: start_fee in /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 1015

![woocommerce product issue billmate](https://cloud.githubusercontent.com/assets/10434920/7114256/0a9c0866-e1dc-11e4-9066-8d8bd0de85a9.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
