### ISSUE TITLE
I noticed an error message in backend in general check out settings.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#65]
Notice: Trying to get property of non-object in /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 362 Fatal error: Uncaught exception 'Exception' with message 'Error in BillmateCalc::getCheapestPClass: Argument sum is not numeric!' in /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/library/billmatecalc.php:532 Stack trace: #0 /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php(365): BillmateCalc::getCheapestPClass(NULL, 0, Array) #1 /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-content/plugins/woocommerce-2.2.11/includes/admin/settings/class-wc-settings-checkout.php(265): WC_Gateway_Billmate_Partpayment->get_title() #2 [internal function]: WC_Settings_Payment_Gateways->payment_gateways_setting(Array) #3 /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-includes/plugin.php(470): call_user_func_array(Array, Array) #4 /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-content/plugins/woocommerce-2.2.11/includes/admin/class-wc-admin-settings.php(618): do in /storage/content/23/107323/wp3.9.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/library/billmatecalc.php on line 532

![woocommerce error backend](https://cloud.githubusercontent.com/assets/10434920/6891542/6052d7b0-d6bc-11e4-9fff-8448d069c95d.png)

**Comment by Boxedsolutions** [comment]
It should be solved now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
