### ISSUE TITLE
4.1.1 - I noticed these error messages in checkout.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#67]
Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-invoice.php on line 300 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 409 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-bankpay.php on line 321 Warning: in_array() expects parameter 2 to be array, null given in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-bankpay.php on line 322 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-invoice.php on line 300 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 409 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-bankpay.php on line 321 Warning: in_array() expects parameter 2 to be array, null given in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-bankpay.php on line 322 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-invoice.php on line 300 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 409 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-bankpay.php on line 321 Warning: in_array() expects parameter 2 to be array, null given in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-bankpay.php on line 322 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-invoice.php on line 300 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 409 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-bankpay.php on line 321 Warning: in_array() expects parameter 2 to be array, null given in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-bankpay.php on line 322 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-invoice.php on line 300 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 409 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-bankpay.php on line 321 Warning: in_array() expects parameter 2 to be array, null given in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-bankpay.php on line 322 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-invoice.php on line 300 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-account.php on line 409 Warning: array_intersect(): Argument #2 is not an array in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-bankpay.php on line 321 Warning: in_array() expects parameter 2 to be array, null given in /storage/content/23/107323/wp4.1.1.boxedtest.se/public_html/wp-content/plugins/woocommerce-gateway-billmate/class-billmate-bankpay.php on line 322

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
