### ISSUE TITLE
3.9 - If you choose to pay with card and then press Cancel, you get sent to cart. Is this correct?

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#69]

**Comment by andyjohansson** [comment]
You should be sent to the checkout, not cart, can this be fixed @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by andyjohansson** [comment]
Also fixed for bank if it was an issue @Boxedsolutions ?

**Comment by Boxedsolutions** [comment]
Fixed for both of course :)

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
