### ISSUE TITLE
Set payment satus

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#7]
Add the function to manually set which order status a new order should have.

**Comment by Boxedsolutions** [comment]
Will find a nice solution for this.

**Comment by Boxedsolutions** [comment]
It references #58 If 58 is done I guess this is ready to

**Comment by joakim-combain** [comment]
This issue is not fixed. As I posted in #58 aswell, our order statuses don't work. I have put all plugins to have Failed payment status.

**Comment by Boxedsolutions** [comment]
When use custom order status, you have to mark custom order status in  the config. I have now checked the checkbox and tested invoice and it works

**Comment by joakim-combain** [comment]
Ah. It seems to be working now. Closing this issue. Closing #58 as well.
