### ISSUE TITLE
Only the cheapest partpayment option should be visible on the prooduct page 

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#70]
Not show all options.

**Comment by Boxedsolutions** [comment]
Should be implemented now

**Comment by andyjohansson** [comment]
Please test @joakim-combain =)

**Comment by joakim-combain** [comment]
Currently shows the most expensive alternative on product page. Also, we show SEK even though store has changed to EUR.

**Comment by Boxedsolutions** [comment]
Partpay doesnt handle Eur, I guess I have to add a little logic that disables this if not SEK. 

But Its not the most expensive alternative, check with SEK and att the same product to cart and checkout, and compare.

**Comment by Boxedsolutions** [comment]
It should be fixed now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
