### ISSUE TITLE
4.1.1 - Discount codes seems to be working weird.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#71]
test123 - becomes 4% on each product. (793515) apilogsid: 30948
teståäö - becomes 19% on each product (732097) apilogsid: 30947
123åäö - becomes 5% on one product and 20% on the other (749183) apilogsid: 30949

**Comment by Boxedsolutions** [comment]
How much is the discount? Does the amounts match?

**Comment by joakim-combain** [comment]
Only for teståäö. All of them should have 19% or amount. The rest seems wrong, I'm not sure tho. But test123 and 123åäö should be amount discounts, so could be an issue with those. Maybe we convert them to % and it's correct.

**Comment by Boxedsolutions** [comment]
Yes its the way I had to solve it. If lets say you have a fixed amount on the cart and the cart has 2 objects with different taxes. I have to calculate the discount percentage per article. If you add the vat and product price on WooCommerce Admin it should match the total value per article in BO

**Comment by joakim-combain** [comment]
Ah ok. Because in the 3.9 version you chose to put it as two seperate products, if I'm not mistaking?

**Comment by Boxedsolutions** [comment]
No not for fixed discounts. Its WooCommerce that makes this subtraction from the product price. It doesnt set any discount code, thats the issue, which did that I need to do it this way.

**Comment by joakim-combain** [comment]
Ah ok. It's fixed then. Closing it.
