### ISSUE TITLE
When I use my person number I'm getting 9003 error message.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#73]
I'm getting this error message when I use 9011203016

Billmate Error Code:9003. The function name is required. Make sure that you provide valid Content-Type and Content-Length in the header.

**Comment by joakim-combain** [comment]
ID and Key I use: 9495 828885158288

apilogsid: 33634

**Comment by Boxedsolutions** [comment]
could you mail me the credentials for that account in BO, i dont have them. jesper@boxedlogistics.se

**Comment by Boxedsolutions** [comment]
Think it would work now.

**Comment by joakim-combain** [comment]
![woocommerce billmate error code encoding issue](https://cloud.githubusercontent.com/assets/10434920/7698077/94f94b48-fe0d-11e4-87ce-99c9a714d660.png)

Error codes seems to be wrong encoded. There is going to be more of them, do you need them as text as well or can you fix all of them with just this one?

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
When I use my pno 9011203016 and accept payment, the error message says "Billmate betalning nekad" without giving the reason for it. We have an error message for this, why are we not using that?

@andyjohansson is it ok if it just says "Billmate betalning nekad"?
