### ISSUE TITLE
Wrong description in Bank. Says Swedbank and SEB when we don't support them.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/woocommerce#74]
says "Direktbetalning med Handelsbanken, Nordea, SEB och Swedbank." sa description text for Description text box.

We should change this and remove SEB and Swedbank since we don't support them.

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
