### ISSUE TITLE
This should be changed to order total not monthly fee

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#77]
![skarmavbild 2015-05-27 kl 17 43 18](https://cloud.githubusercontent.com/assets/4968755/7840500/f001b6b6-0497-11e5-8148-def713852e8f.png)

**Comment by Boxedsolutions** [comment]
This is for Product page and show partpay from, its possible to choose a price interval to show the partpayment info on.

**Comment by andyjohansson** [comment]
Then I follow. There are a capital P on "Produktens". Could you fix that? And one should be "lägre" and one of them "higher".

**Comment by Boxedsolutions** [comment]
It should be fixed
