### ISSUE TITLE
Change partpayment on product page & overview

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#79]
This should be changed: (Product page)
Delbetala från 270 SEK/månad.
Test Billmate - 270 SEK/månad

Should only say:
Swe:
Delbetala från 270 kr / månad. (SEK if kr is not available)

Eng:
Part pay from 270 SEK / mounth

(Always display the cheepest one)
(This should be the standard) I know that I can customize it. Same setting for both.

**Comment by andyjohansson** [comment]
Change standard from this:
[billmate_img]<br />Delbetala från [billmate_price] [billmate_currency]/månad.<br />[billmate_partpayment_info_link]

To this:

[billmate_img]<br />Delbetala från [billmate_price] [billmate_currency]/månad.

**Comment by andyjohansson** [comment]
On overview page:
From this:
Från [billmate_price] [billmate_currency]/månad

To this:
Delbetala från [billmate_price] [billmate_currency]/månad.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Trust you that it´s fixed since it´s hard to verify.
