### ISSUE TITLE
Improve layout

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#80]
* Why do we display the payment plan to the right?
* Dropdown should have bigger with so that the whole text will fit.
* Person / Organisationsnummer should be:
Swe:
Person / Org. Nummer
Eng:
Social Security No. / Org. No.

![skarmavbild 2015-05-27 kl 17 52 34](https://cloud.githubusercontent.com/assets/4968755/7840753/2f8c2284-0499-11e5-8f31-4fb0dddc28cb.png)

**Comment by Boxedsolutions** [comment]
Removed the text to the right and resized the dropdown a little bit.
