### ISSUE TITLE
Implement same "accept terms & conditions" as in Magento

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#81]
Use the same text and logic. PM me if you need to discuss this.

**Comment by andyjohansson** [comment]
Example for the logic:
"Min e-post, , är korrekt och får användas för fakturering. Jag godkänner även köpvillkor för fakturabetalning."

**Comment by Boxedsolutions** [comment]
I dont get it. In my eyes its pretty the same.
![skarmklipp 2015-05-28 08 41 33](https://cloud.githubusercontent.com/assets/8977650/7854017/726cf160-0515-11e5-9fee-53587cc22d0d.png)
