### ISSUE TITLE
This script needs to be included correctly with wp_enqueue_script

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#84]
jQuery(document).ready(function(){
	window.$ = $ = jQuery;

    $.getScript("https://efinance.se/billmate/base.js", function(){
		    $("#billmate_partpayment").Terms("villkor_delbetalning",{eid: billmate_eid,effectiverate:34}, "#billmate_partpayment");
    });
});

Exists in the following files:
woocommerce-gateway-billmate/shortcodes.php 
woocommerce-gateway-billmate/class-billmate-invoice.php 
woocommerce-gateway-billmate/class-billmate-account.php

**Comment by andyjohansson** [comment]
https://codex.wordpress.org/Function_Reference/wp_enqueue_script

**Comment by Boxedsolutions** [comment]
Will move it to the billmatepopup file. We set the billmate_id to a javascript variable and it should work better.

**Comment by andyjohansson** [comment]
Is it like this now?

**Comment by Boxedsolutions** [comment]
I have moved this parts to billmatepopup.js instead.

**Comment by andyjohansson** [comment]
Ok, but is billmatepopup.js included the correct wordpress way with https://codex.wordpress.org/Function_Reference/wp_enqueue_script?

**Comment by Boxedsolutions** [comment]
wp_register_script( 'billmate-popup-js', plugins_url( '/js/billmatepopup.js', __FILE__ ),array(),false, true );
wp_enqueue_script( 'billmate-popup-js' );

Its done as above

**Comment by andyjohansson** [comment]
Super, closing then.
