### ISSUE TITLE
Missing translation of description in back-end

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#88]
<img width="1241" alt="skarmavbild 2015-07-31 kl 13 36 38" src="https://cloud.githubusercontent.com/assets/4968755/9006574/34773a86-3789-11e5-9061-b24d5b33bf77.png">

English: Receive payments on your WooCommerce store via Billmate. Invoice, partpayment, credit/debit card and direct bank transfers. Secure and 100% free plugin.

Swedish: Ta betalt i din WooCommerce butik med Billmate. Faktura, delbetalning, kredit/debit kort och direkt bankbetalning. Säkert och 100% gratis plugin.

**Comment by Boxedsolutions** [comment]
http://wordpress.stackexchange.com/questions/25636/localize-plugin-description Seems to need another plugin or do you have the solution?

**Comment by andyjohansson** [comment]
Are you sure?
https://codex.wordpress.org/Writing_a_Plugin#Internationalizing_Your_Plugin

**Comment by Boxedsolutions** [comment]
I did even try to add a dummy translation in init after load_plugin_textdomain, didnt work.

<img width="848" alt="skarmavbild 2015-08-03 kl 09 27 36" src="https://cloud.githubusercontent.com/assets/8977650/9032757/1f98b410-39c2-11e5-8b92-18c99704861e.png">

**Comment by andyjohansson** [comment]
Also checkout https://codex.wordpress.org/I18n_for_WordPress_Developers

**Comment by andyjohansson** [comment]
Pushing this to future release to see if we can fix it.
