### ISSUE TITLE
What is the standard text for Billmate Partpayment?

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#89]
Should there really be a dash?
<img width="484" alt="skarmavbild 2015-07-31 kl 13 54 05" src="https://cloud.githubusercontent.com/assets/4968755/9006806/b9d8df2a-378b-11e5-91ff-2b2ffb72b37f.png">

Also maybe change the gateway_id from billmate to billmate_invoice?

**Comment by Boxedsolutions** [comment]
Can you please Explain this?

**Comment by andyjohansson** [comment]
Shouldn't it be like this:
Billmate - Delbetalning --> Billmate Delbetalning (then it´s the same way as the other modules?)

And the gateway_name convention is not clear for invoice. billmate should be called billmate_invoice?

**Comment by Boxedsolutions** [comment]
Should be fixed
