### ISSUE TITLE
Remove "betalningsåtgärd" on bank payments

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#90]
Should always reserve the amount.
<img width="627" alt="skarmavbild 2015-07-31 kl 13 55 44" src="https://cloud.githubusercontent.com/assets/4968755/9006825/e313a5be-378b-11e5-83de-30621b2895d1.png">

**Comment by Boxedsolutions** [comment]
is Fixed

**Comment by andyjohansson** [comment]
Don´t send autoactivate = 1 on the bankpayments.

params
{ "PaymentData": { "method": 16, "currency": "SEK", "language": "sv", "country": "SE", "autoactivate": 1, "orderid": "63" },

**Comment by Boxedsolutions** [comment]
should be fixed

**Comment by andyjohansson** [comment]
Will relink id & secret to test.

**Comment by andyjohansson** [comment]
Verified.
