### ISSUE TITLE
Redo custom order status

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#91]
Anpassad order status
Swe: Anpassad godkänd orderstatus
Eng: Custom approved order status

Redo this so that we only have the dropdown and not the checkbox. This is true for all payment methods.
Default setting is WooCommerce standard.

<img width="1222" alt="skarmavbild 2015-07-31 kl 13 57 40" src="https://cloud.githubusercontent.com/assets/4968755/9006856/242ab718-378c-11e5-803c-f7c6567af819.png">

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Not correct yet...

Order status:
Swe: Anpassad godkänd orderstatus
Eng: Custom approved order status

<img width="1221" alt="skarmavbild 2015-08-03 kl 08 55 16" src="https://cloud.githubusercontent.com/assets/4968755/9032287/62ef7a32-39bd-11e5-900e-4330c5fb6b46.png">

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Translation to swedish only working on invoice settings page. Not partpayment, card & bank.
