### ISSUE TITLE
Can we somehow get so that the Billmate Gateways are displayed first here?

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#93]
Billmate order should be:
Invoice
Part Payment
Card
Bank

<img width="1045" alt="skarmavbild 2015-07-31 kl 14 04 23" src="https://cloud.githubusercontent.com/assets/4968755/9006958/1913f4ec-378d-11e5-82f9-5ff348ed1b27.png">

**Comment by Boxedsolutions** [comment]
Is it sort order that sets this?

**Comment by Boxedsolutions** [comment]
It is Possible with a filter, but then the customer cant change the order self.

**Comment by andyjohansson** [comment]
What do you mean by cant change the order self?

**Comment by Boxedsolutions** [comment]
Isnt Possible as WooCommerce sorts by Alphabetic
