### ISSUE TITLE
Translate "Lägg till en fakturaavgift utan moms, lämna tomt för att inaktivera"

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#95]
Lägg till en fakturaavgift ex. moms, lämna tomt för att inaktivera.

**Comment by Boxedsolutions** [comment]
is Fixed

**Comment by andyjohansson** [comment]
We are missing a point after these three sentences.
<img width="970" alt="skarmavbild 2015-08-03 kl 09 25 14" src="https://cloud.githubusercontent.com/assets/4968755/9032709/968ae1de-39c1-11e5-9b13-ab51967d274b.png">

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
No? Look at the top one?
<img width="970" alt="skarmavbild 2015-08-03 kl 11 39 26" src="https://cloud.githubusercontent.com/assets/4968755/9034998/52c00606-39d4-11e5-8618-5c3d6126c3a0.png">

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Please look at all the sentences in the back-end. There are a couple of places where there are no dots.

**Comment by Boxedsolutions** [comment]
Will do.

**Comment by Boxedsolutions** [comment]
I have checked and updated the ones I saw.

**Comment by andyjohansson** [comment]
Looks good, closing.
