### ISSUE TITLE
Fix partpayment front-end

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#98]
1. Betalplan = Delbetalningsalternativ
2. The selectbox for part payment options should be on 1 row.
3. If get adress is active the personnummer / organisationsnummer should not be visible (same logic as on Magento with mandatory and so on)
4. If get adress is inactive the "Personnummer / Organisationsnummer" should be on one row.
5. A space to much before "köpvillkoren" and no mix between swedish and english. Also remove the dot after "köpvillkoren".

![skarmavbild 2015-07-31 kl 15 23 20](https://cloud.githubusercontent.com/assets/4968755/9008101/1cfa337c-3798-11e5-9153-df0ddb1892a1.png)

**Comment by Boxedsolutions** [comment]
Applied a fix

**Comment by andyjohansson** [comment]
Fixed.
