### ISSUE TITLE
By default the sort order of Billmate modules should be this in front-end

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/woocommerce#99]
Invoice
Part Payment
Card
Bank

**Comment by Boxedsolutions** [comment]
It seems that if I implement it the clients cant change it in some way.

**Comment by andyjohansson** [comment]
Can't we set the default sort order somehow and so that they can change it?

**Comment by Boxedsolutions** [comment]
I think i need to implement a filter and that way its not possible for the client to change, to add a checkbox for customizing payment gateway sort order will not be good user experience.

**Comment by andyjohansson** [comment]
The user changes the sort order here: 
<img width="1273" alt="skarmavbild 2015-08-03 kl 09 05 42" src="https://cloud.githubusercontent.com/assets/4968755/9032428/d8d024b2-39be-11e5-9f33-26fd184dc317.png">
How is this sorted by default? Is it by ID, name or how? Then we can fix it if it´s default sorted by ID.

**Comment by Boxedsolutions** [comment]
But if we add a filter that sorts the payment alternatives after this, This grid will be of no use?

**Comment by andyjohansson** [comment]
I don´t want to sort if after, I just want the default add order to that list.
